import type { Draft, Product } from '../../../shared/model';
import { displayProducts } from '../../../shared/product-display';
import { materialImage } from '../../materials-render';
import { pawfectStyles } from '../pawfectGroom';
import { buildThemeContext, esc, productPath, type ThemeContext } from '../types';
import { pawfectMaterialsRevision } from './materials';

export const isPawfectMaterials = (draft: Draft) => draft.template === 'pawfect-groom' && draft.materials?.contractRevision === pawfectMaterialsRevision;
const heart = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M12 21C4 15 1 11 3 6c2-4 7-4 9 0 2-4 7-4 9 0 2 5-1 9-9 15Z"/></svg>';
const lines = (value: string) => value.split(/\r?\n/).map(line => line.trim()).filter(Boolean);
const multiline = (value: string) => esc(value).replace(/\r?\n/g, '<br>');

/** Only revision 2 uses this renderer. Slot IDs, product IDs and semantic copy regions are the executable boundary. */
export function renderPawfectMaterialsPage(ctx: ThemeContext): string {
  const { draft, options, lang, page, path, navPath, navAttrs, translateProduct } = ctx;
  const materials = draft.materials!;
  const displayedProducts = displayProducts(draft);
  const canonicalId = (id?: string) => id && (displayedProducts.some(product => product.id === id) ? id : draft.productDisplayGroups?.find(group => group.includes(id))?.[0] || id);
  const text = (id: string) => materials.textBindings.find(binding => binding.slotId === id && binding.locale === lang)?.text || '';
  const mark = (id: string) => `data-wr-material-text="${esc(id)}"`;
  const route = (target: string, label: string, cls = '', productId?: string, slotId?: string) => {
    const href = path(target === 'detail' ? productPath(productId) : navPath(target)) + (target === 'contact' && productId ? `?productId=${encodeURIComponent(canonicalId(productId)!)}` : '');
    return `<a class="${esc(cls)}" href="${esc(href)}" ${navAttrs(target, productId)}${page === target ? ' aria-current="page"' : ''}${slotId ? ` ${mark(slotId)}` : ''}>${esc(label)}</a>`;
  };
  const action = (id = 'cta-button', productId?: string) => route('contact', `${text(id) || ctx.ui.inquire} ↗`, 'pg-button', productId, id);
  const photo = (slotId: string, productId?: string, eager = false) => {
    const binding = materials.imageBindings.find(binding => binding.slotId === slotId && (!productId || binding.productId === productId));
    if (!binding) throw new Error(`Missing validated Pawfect materials binding ${slotId}:${productId || ''}`);
    const image = materialImage(binding, { ...options, lang }).replace('<img ', `<img data-wr-material-image="${esc(slotId)}"${binding.productId ? ` data-wr-material-product="${esc(binding.productId)}"` : ''} `);
    return eager ? image.replace('loading="lazy"', 'fetchpriority="high" loading="eager"') : image;
  };
  const selected = (group: 'scene' | 'featured') => {
    const ids = materials.displaySelection?.[group === 'scene' ? 'sceneProductIds' : 'featuredProductIds'] || [];
    const products = ids.map(id => draft.products.find(product => product.id === (group === 'featured' ? canonicalId(id) : id))).filter((product): product is Product => !!product);
    return group === 'featured' ? products.filter((product, index) => products.findIndex(other => other.id === product.id) === index) : products;
  };
  const heading = (region: string) => `<div class="pg-section-title"><span class="pg-eyebrow" ${mark(`${region}-eyebrow`)}>${esc(text(`${region}-eyebrow`))}</span><h2 ${mark(`${region}-headline`)}>${multiline(text(`${region}-headline`))}</h2><p ${mark(`${region}-description`)}>${esc(text(`${region}-description`))}</p></div>`;
  const pageHeading = (region: 'about' | 'contact') => `<section class="pg-section pg-page-heading" data-wr-hero data-wr-material-region="${region}-heading"><div class="wr-confirmed-hero-copy"><span class="pg-eyebrow" ${mark(`${region}-eyebrow`)}>${esc(text(`${region}-eyebrow`))}</span><h1><span ${mark(`${region}-headline`)}>${multiline(text(`${region}-headline`))}</span><br><em ${mark(`${region}-emphasis`)}>${multiline(text(`${region}-emphasis`))}</em></h1><p ${mark(`${region}-description`)}>${esc(text(`${region}-description`))}</p></div></section>`;
  const catalog = (products: Product[]) => `<section class="pg-section${page === 'catalog' ? ' pg-tight' : ''}" id="collections" data-wr-material-region="catalog">${page === 'home' ? heading('catalog') : ''}<div class="pg-services" data-wr-product-list="${page}" data-product-count="${products.length}">${products.map((product, index) => {
    const translated = translateProduct(product);
    const summary = product.tagline || translated.description;
    return `<article class="pg-service" data-wr-product-card data-reveal="fade-up" data-wr-product-id="${esc(product.id)}"><span class="pg-number">${String(index + 1).padStart(2, '0')} ${heart}</span><a class="pg-main-image" href="${esc(path(productPath(product.id)))}" ${navAttrs('detail', product.id)}>${photo('product-main', product.id)}</a>${product.sellingPoints?.[0] ? `<span class="pg-card-label">${esc(product.sellingPoints[0])}</span>` : ''}<h3>${esc(translated.name)}</h3>${summary ? `<p>${esc([...summary].length > 180 ? [...summary].slice(0, 180).join('') + '…' : summary)}</p>` : ''}${product.dimensions ? `<p class="pg-small">${esc(product.dimensions)}</p>` : ''}${route('detail', `${ctx.ui.details} ↗`, 'pg-text-link', product.id)}</article>`;
  }).join('')}</div>${page === 'home' && products.length < displayedProducts.length ? route('catalog', `${ctx.ui.catalog} ↗`, 'pg-text-link') : ''}</section>`;
  const feature = (slotId = 'feature-scene') => `<section class="pg-section pg-why" data-wr-material-region="feature"><div class="pg-why-copy"><span class="pg-eyebrow" ${mark('feature-eyebrow')}>${esc(text('feature-eyebrow'))}</span><h2 ${mark('feature-headline')}>${multiline(text('feature-headline'))}</h2><ul ${mark('feature-points')}>${lines(text('feature-points')).map(point => `<li><span aria-hidden="true">✓</span>${esc(point)}</li>`).join('')}</ul>${route('about', `${text('feature-link')} ↗`, 'pg-text-link', undefined, 'feature-link')}</div><div class="pg-scene-media">${photo(slotId)}</div></section>`;
  const gallery = () => `<section class="pg-section pg-gallery-section" id="gallery" data-wr-material-region="gallery">${heading('gallery')}<div class="pg-gallery" data-product-count="${selected('scene').length}" tabindex="0" aria-label="${esc(text('gallery-headline'))}">${selected('scene').map(product => `<figure data-wr-product-id="${esc(product.id)}">${photo('gallery-scene', product.id)}<figcaption>${esc(translateProduct(product).name)}${product.tagline ? ` · ${esc(product.tagline)}` : ''}</figcaption></figure>`).join('')}</div></section>`;
  const categories = () => `<section class="pg-section pg-breeds" data-wr-material-region="categories">${heading('categories')}<div class="pg-three" data-product-count="${selected('scene').length}">${selected('scene').map(product => `<article>${heart}<h3>${esc(translateProduct(product).name)}</h3>${product.tagline ? `<p>${esc(product.tagline)}</p>` : ''}${route('detail', `${ctx.ui.details} ↗`, 'pg-text-link', product.id)}</article>`).join('')}</div></section>`;
  const faq = () => `<section class="pg-section pg-faq" id="faq" data-wr-material-region="faq"><div>${heading('faq')}${route('contact', `${ctx.ui.contact} ↗`, 'pg-text-link')}</div><div>${Array.from({ length: 4 }, (_, index) => `<details><summary ${mark(`faq-question-${index + 1}`)}>${esc(text(`faq-question-${index + 1}`))}<span aria-hidden="true">+</span></summary><p ${mark(`faq-answer-${index + 1}`)}>${esc(text(`faq-answer-${index + 1}`))}</p></details>`).join('')}</div></section>`;
  const process = () => `<section class="pg-section pg-next-steps" aria-label="${esc(ctx.ui.contact)}"><div class="pg-three">${[
    [ctx.ui.catalog, ctx.ui.details, route('catalog', `${ctx.ui.discover} ↗`, 'pg-text-link')],
    [ctx.ui.inquire, ctx.ui.contactIntro, action()],
    [ctx.ui.contact, ctx.ui.emailDirect, draft.company.email ? `<a class="pg-text-link" href="mailto:${esc(draft.company.email)}">${esc(draft.company.email)}</a>` : ''],
  ].map(([title, description, link], index) => `<article class="pg-process"><span class="pg-step">${String(index + 1).padStart(2, '0')}</span><h3>${esc(title)}</h3><p>${esc(description)}</p>${link}</article>`).join('')}</div></section>`;
  let body = '';
  if (page === 'home') {
    body = `<section class="pg-section pg-hero" data-wr-hero data-wr-material-region="hero"><div class="pg-hero-copy"><div class="wr-confirmed-hero-copy"><span class="pg-eyebrow" ${mark('hero-eyebrow')}>${heart}${esc(text('hero-eyebrow'))}</span><h1><span ${mark('hero-headline')}>${multiline(text('hero-headline'))}</span><br><em ${mark('hero-emphasis')}>${multiline(text('hero-emphasis'))}</em></h1><p ${mark('hero-subtitle')}>${esc(text('hero-subtitle'))}</p><div class="pg-actions">${route('catalog', `${text('primary-cta')} ↗`, 'pg-button', undefined, 'primary-cta')}<a class="pg-button pg-secondary" href="#gallery" ${mark('hero-secondary-cta')}>${esc(text('hero-secondary-cta'))} ↗</a></div><div class="pg-trust" ${mark('hero-trust-lines')}>${lines(text('hero-trust-lines')).map(value => `<span>${heart}${esc(value)}</span>`).join('')}</div></div></div><div class="pg-hero-art"><div class="pg-portrait">${photo('hero-portrait', undefined, true)}</div><span class="pg-orbit">${heart}<span ${mark('hero-orbit')}>${multiline(text('hero-orbit'))}</span></span><span class="pg-photo-tag" ${mark('hero-photo-tag')}>${esc(text('hero-photo-tag'))}</span></div></section><div class="pg-ribbon">${lines(text('hero-trust-lines')).map(value => `<span>${esc(value)}</span>${heart}`).join('')}</div>${catalog(selected('featured'))}${feature()}${gallery()}${categories()}${faq()}`;
  }
  if (page === 'catalog') body = `<section class="pg-section pg-page-heading" data-wr-hero><div class="wr-confirmed-hero-copy"><span class="pg-eyebrow" ${mark('catalog-eyebrow')}>${esc(text('catalog-eyebrow'))}</span><h1 ${mark('catalog-headline')}>${multiline(text('catalog-headline'))}</h1><p ${mark('catalog-description')}>${esc(text('catalog-description'))}</p></div></section>${catalog(displayedProducts)}${process()}${categories()}${faq()}`;
  if (page === 'detail') {
    const product = draft.products.find(product => product.id === options.productId);
    body = product ? `<section class="pg-section pg-detail" data-wr-material-region="detail"><div>${photo('product-main', product.id, true).replace('<img ', '<img id="wr-detail-main-img" ')}</div><div>${route('catalog', `← ${ctx.ui.back}`, 'pg-text-link')}<h1>${esc(translateProduct(product).name)}</h1>${product.tagline ? `<p class="pg-chip">${esc(product.tagline)}</p>` : ''}${translateProduct(product).description ? `<p>${esc(translateProduct(product).description)}</p>` : ''}${product.sellingPoints?.length ? `<ul class="pg-checks">${product.sellingPoints.map(point => `<li>✓ ${esc(point)}</li>`).join('')}</ul>` : ''}${product.material || product.dimensions ? `<dl>${product.material ? `<dt>${esc(ctx.ui.material)}</dt><dd>${esc(product.material)}</dd>` : ''}${product.dimensions ? `<dt>${esc(ctx.ui.dimensions)}</dt><dd>${esc(product.dimensions)}</dd>` : ''}</dl>` : ''}${action('cta-button', product.id)}</div></section>${process()}` : `<section class="pg-section pg-page-heading"><h1>${esc(ctx.ui.noProducts)}</h1>${route('catalog', ctx.ui.catalog, 'pg-button')}</section>`;
  }
  if (page === 'about') {
    const companyAbout = text('company-about') || draft.company.description;
    const companySection = companyAbout || draft.company.capabilities || draft.company.certifications ? `<div class="pg-company-note"><h3 ${mark('company-section-title')}>${esc(text('company-section-title'))}</h3>${companyAbout ? `<p ${mark('company-about')}>${esc(companyAbout)}</p>` : ''}${draft.company.capabilities ? `<p>${esc(draft.company.capabilities)}</p>` : ''}${draft.company.certifications ? `<p>${esc(draft.company.certifications)}</p>` : ''}</div>` : '';
    body = `${pageHeading('about')}${feature('about-primary-image')}<section class="pg-section pg-about-story" data-wr-material-region="about"><div>${photo('about-secondary-image')}</div><div><h2 ${mark('about-story-headline')}>${multiline(text('about-story-headline'))}</h2><p ${mark('about-story')}>${esc(text('about-story'))}</p>${companySection}</div></section>${process()}${gallery()}`;
  }
  if (page === 'contact') {
    const company = draft.company;
    const inquiryForm = buildThemeContext({ ...draft, products: displayedProducts }, { ...options, productId: canonicalId(options.productId) }).inquiryFormHtml;
    body = `${pageHeading('contact')}<section class="pg-section pg-contact pg-tight" data-wr-material-region="contact"><aside><h2>${esc(ctx.ui.contact)}</h2><div class="pg-company-note"><p>${esc(company.name)}</p>${company.contactName ? `<p>${esc(company.contactName)}</p>` : ''}${company.email ? `<a href="mailto:${esc(company.email)}">${esc(company.email)}</a>` : ''}${company.phone ? `<p><a href="tel:${esc(company.phone.replace(/[^+\d]/g, ''))}">${esc(company.phone)}</a></p>` : ''}${company.address ? `<p>${esc(company.address)}</p>` : ''}</div><div class="pg-contact-media">${photo('contact-scene')}</div></aside><div class="pg-form"><h2 ${mark('contact-form-headline')}>${esc(text('contact-form-headline'))}</h2><p ${mark('contact-form-description')}>${esc(text('contact-form-description'))}</p>${inquiryForm}</div></section>${faq()}`;
  }
  const logo = draft.company.logoAssetId ? ctx.brandLogo : `${heart}<span>${esc(draft.company.name)}</span>`;
  const anchor = (id: string, label: string) => {
    const local = page === 'home' || (id === 'gallery' && page === 'about') || (id === 'faq' && ['catalog', 'contact'].includes(page));
    return `<a href="${local ? '' : esc(path('index.html'))}#${id}"${local ? '' : ` ${navAttrs('home')}`}>${esc(label)}</a>`;
  };
  return `<a class="pg-skip" href="#main">${esc(ctx.ui.skip)}</a><header class="pg-header"><a class="pg-brand" href="${esc(path('index.html'))}" ${navAttrs('home')}>${logo}</a><nav aria-label="${esc(ctx.ui.menu)}">${route('catalog', ctx.ui.catalog)}${route('about', ctx.ui.about)}${anchor('gallery', text('gallery-eyebrow'))}${anchor('faq', text('faq-eyebrow'))}</nav><div class="pg-header-right">${draft.languages.length > 1 ? `<div class="pg-languages">${ctx.languageLinks}</div>` : ''}${action()}</div></header><main id="main">${body}</main><section class="pg-booking" data-wr-material-region="cta"><div><span class="pg-eyebrow" ${mark('cta-eyebrow')}>${esc(text('cta-eyebrow'))}</span><h2 ${mark('cta-headline')}>${multiline(text('cta-headline'))}</h2><p ${mark('cta-description')}>${esc(text('cta-description'))}</p></div><div>${action()}${draft.company.phone ? `<a class="pg-call" href="tel:${esc(draft.company.phone.replace(/[^+\d]/g, ''))}">${esc(draft.company.phone)} ↗</a>` : ''}</div></section><footer class="pg-footer"><a class="pg-brand" href="${esc(path('index.html'))}" ${navAttrs('home')}>${logo}</a><div>${route('catalog', ctx.ui.catalog)}${route('about', ctx.ui.about)}${route('contact', ctx.ui.contact)}${ctx.socials}</div><p>© ${new Date().getUTCFullYear()} ${esc(draft.company.name)} · ${esc(ctx.ui.rights)}</p></footer>`;
}

/** The historical stylesheet is untouched. These rules apply only to revision 2. */
export const pawfectMaterialsStyles = `${pawfectStyles}
body.wr-pawfect-materials{background:var(--pg-background,#faf8f3);color:var(--pg-text,#203337)}
.wr-pawfect-materials p{color:var(--pg-muted,#617071)}.wr-pawfect-materials em{color:var(--pg-primary,#327f85)}
.wr-pawfect-materials :is(h1,h2,h3,p,a,span,dd){overflow-wrap:anywhere}.wr-pawfect-materials :is(.pg-hero-copy,.pg-hero-art,.pg-services>*,.pg-about-story>*,.pg-detail>*,.pg-contact>*){min-width:0}
.wr-pawfect-materials .pg-header nav a{overflow-wrap:normal}
.wr-pawfect-materials .pg-hero{grid-template-columns:minmax(0,1.08fr) minmax(0,1fr)}
.wr-pawfect-materials .pg-hero-copy .wr-confirmed-hero-copy>p{margin:25px 0 30px;max-width:420px;font-size:16px}.wr-pawfect-materials .wr-confirmed-hero-copy>.button{display:inline-flex;margin-top:20px;padding:15px 23px;border-radius:100px;background:var(--pg-primary,#327f85);color:var(--pg-ink,#fff);font-size:13px;font-weight:700;line-height:1.5}
.wr-pawfect-materials .pg-portrait{width:100%;overflow:hidden}.wr-pawfect-materials .pg-portrait :is(img,picture){display:block;width:100%;height:100%}.wr-pawfect-materials .pg-portrait img{object-fit:cover}
.wr-pawfect-materials .pg-hero h1 em:after{background:var(--pg-secondary,#c9833a)}.wr-pawfect-materials .pg-orbit{background:var(--pg-badge,#f2d598)}
body.wr-pawfect-materials.wr-brand-color .pg-hero h1 em:after{background-color:var(--pg-secondary,#c9833a)!important}
body.wr-pawfect-materials.wr-brand-color .pg-form{background-color:#fff!important;border-color:#e2e1d7!important}body.wr-pawfect-materials.wr-brand-color .pg-contact aside{background-color:transparent!important}
body.wr-pawfect-materials.wr-brand-color .pg-booking .pg-button{background-color:var(--pg-background,#faf8f3)!important;color:var(--pg-primary,#327f85)!important;border-color:var(--pg-background,#faf8f3)!important}
body.wr-pawfect-materials.wr-brand-color .pg-footer .pg-brand svg{color:#c7e1d9!important}.wr-pawfect-materials .pg-footer>p{color:#bad0cc}
.wr-pawfect-materials .pg-services{grid-template-columns:repeat(3,minmax(0,1fr));align-items:stretch}.wr-pawfect-materials .pg-service{display:flex;flex-direction:column;background:var(--pg-surface,#f0eee6)}.wr-pawfect-materials .pg-service h3{font-size:23px;min-height:52px}.wr-pawfect-materials .pg-service p{margin-bottom:14px}.wr-pawfect-materials .pg-service .pg-text-link{margin-top:auto;padding-top:16px}.wr-pawfect-materials .pg-number{margin-bottom:23px}
.wr-pawfect-materials :is(.pg-services,.pg-breeds .pg-three)[data-product-count="1"]{grid-template-columns:minmax(0,1fr);max-width:420px;margin-inline:auto}.wr-pawfect-materials :is(.pg-services,.pg-breeds .pg-three)[data-product-count="2"]{grid-template-columns:repeat(2,minmax(0,1fr));max-width:820px;margin-inline:auto}.wr-pawfect-materials .pg-gallery[data-product-count="1"]{max-width:420px;margin-inline:auto}
.wr-pawfect-materials .pg-main-image{display:block;width:calc(100% + 56px);margin:0 -28px 24px;background:#fff}.wr-pawfect-materials .pg-main-image :is(img,picture){display:block;width:100%}.wr-pawfect-materials .pg-main-image img{height:auto;aspect-ratio:3/2;object-fit:contain}.wr-pawfect-materials .pg-card-label{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.1em;color:var(--pg-secondary,#c9833a);margin-bottom:11px}
.wr-pawfect-materials .pg-why{background:transparent}.wr-pawfect-materials .pg-why-copy{background:var(--pg-primary,#327f85)}.wr-pawfect-materials .pg-why-copy :is(h2,li,a){color:var(--pg-ink,#fff)}.wr-pawfect-materials .pg-why-copy>.pg-eyebrow{color:var(--pg-ink,#fff);margin-bottom:18px}.wr-pawfect-materials .pg-why-copy ul{margin:25px 0 30px}
.wr-pawfect-materials .pg-scene-media{height:100%;min-height:440px;overflow:hidden;border-radius:0 16px 16px 0}.wr-pawfect-materials .pg-scene-media :is(img,picture){display:block;width:100%;height:100%}.wr-pawfect-materials .pg-scene-media img{object-fit:cover}
.wr-pawfect-materials .pg-gallery{grid-auto-columns:minmax(0,1fr);gap:22px;padding-bottom:8px}.wr-pawfect-materials .pg-gallery figure{height:auto!important;overflow:visible;min-width:0}.wr-pawfect-materials .pg-gallery figure:nth-child(even){margin-top:25px}.wr-pawfect-materials .pg-gallery img{aspect-ratio:4/5;width:100%;height:auto;border-radius:12px}.wr-pawfect-materials .pg-gallery figcaption{font-size:11px;color:var(--pg-muted,#617071);padding-top:13px}.wr-pawfect-materials .pg-gallery img:hover{transform:none}
.wr-pawfect-materials .pg-about-story>div>img{aspect-ratio:3/2}.wr-pawfect-materials .pg-about-story h2{margin-bottom:25px}.wr-pawfect-materials .pg-company-note{border:1px solid #dedfd3;background:var(--pg-surface,#f0eee6);padding:30px;border-radius:14px}.wr-pawfect-materials .pg-company-note h3{font-size:22px;margin-bottom:13px}.wr-pawfect-materials .pg-contact-media{margin-top:30px}.wr-pawfect-materials .pg-contact-media img{width:100%;height:auto;aspect-ratio:6/5;border-radius:15px}
.wr-pawfect-materials .pg-detail>div>img{object-fit:contain;background:white;aspect-ratio:3/2;max-height:none}.wr-pawfect-materials .pg-detail dl{display:grid;grid-template-columns:90px minmax(0,1fr);gap:10px 20px;border-top:1px solid #dde0d5;padding-top:20px;font-size:13px}.wr-pawfect-materials .pg-detail dd{margin:0;color:var(--pg-muted,#617071)}.wr-pawfect-materials .pg-detail dt{font-weight:700}.wr-pawfect-materials .pg-booking{background:var(--pg-primary,#327f85)}.wr-pawfect-materials .pg-booking :is(h2,p){color:var(--pg-ink,#fff)}.wr-pawfect-materials .pg-ribbon{gap:35px}
@media(max-width:950px) and (min-width:601px){.wr-pawfect-materials .pg-service{padding:22px}.wr-pawfect-materials .pg-main-image{width:calc(100% + 44px);margin-left:-22px;margin-right:-22px}.wr-pawfect-materials .pg-service h3{font-size:19px;min-height:64px}}
@media(max-width:600px){.wr-pawfect-materials .pg-hero{grid-template-columns:1fr}.wr-pawfect-materials .pg-hero-copy .wr-confirmed-hero-copy>p{font-size:14px;margin:25px 0}.wr-pawfect-materials .pg-services,.wr-pawfect-materials :is(.pg-services,.pg-breeds .pg-three)[data-product-count="2"]{grid-template-columns:1fr}.wr-pawfect-materials .pg-main-image{width:calc(100% + 50px);margin-left:-25px;margin-right:-25px}.wr-pawfect-materials .pg-service h3{min-height:0}.wr-pawfect-materials .pg-gallery{grid-auto-columns:78%;gap:18px}.wr-pawfect-materials .pg-gallery[data-product-count="1"]{grid-auto-columns:100%}.wr-pawfect-materials .pg-scene-media{min-height:0;border-radius:0 0 16px 16px}.wr-pawfect-materials .pg-scene-media img{height:auto;aspect-ratio:6/5}.wr-pawfect-materials .pg-header nav{gap:22px}.wr-pawfect-materials .pg-header .pg-button{padding:10px 13px}.wr-pawfect-materials .pg-company-note{padding:25px}.wr-pawfect-materials .pg-detail h1{font-size:35px}}
`;

export function pawfectMaterialsPalette(draft: Draft): string {
  const palette = draft.materials!.visual.palette;
  const color = (value: string, fallback: string) => /^#[a-f\d]{6}$/i.test(value) ? value : fallback;
  return `--pg-primary:${color(draft.brandColor || palette.primary, '#327f85')};--pg-secondary:${color(palette.secondary, '#c9833a')};--pg-background:${color(palette.background, '#faf8f3')};--pg-surface:${color(palette.surface, '#f0eee6')};--pg-text:${color(palette.text, '#203337')};--pg-muted:${color(palette.mutedText, '#617071')};`;
}
