import type { Language } from '../shared/model';
export const labels = {
  en: {
    home: 'Home',
    catalog: 'Collection',
    about: 'Our company',
    contact: 'Contact',
    details: 'View product',
    inquire: 'Ask about this product',
    material: 'Material',
    dimensions: 'Dimensions',
    name: 'Your name',
    email: 'Email address',
    company: 'Company',
    message: 'Your message',
    send: 'Send inquiry',
    sending: 'Sending…',
    sent: 'Your inquiry has been saved. Thank you.',
    failed: 'Unable to save your inquiry. Please try again.',
    preview: 'Private preview · inquiry sending is disabled',
    products: 'Our products',
    discover: 'Discover the collection',
    conversation: 'Let’s start a conversation.',
    contactIntro: 'Tell us what you are looking for.',
    product: 'Product',
    optional: 'Optional',
    allProducts: 'All products',
    trader: 'Trading company',
    factory: 'Manufacturer',
    back: 'Back to collection',
    pause: 'Pause video',
    play: 'Play video',
    language: 'Language',
    skip: 'Skip to content',
    unavailable: 'Image coming soon',
    noProducts: 'Products will appear here.',
    related: 'More to explore',
    emailDirect: 'Or email us directly',
    rights: 'All rights reserved',
    menu: 'Navigation',
  },
  de: {
    home: 'Startseite',
    catalog: 'Kollektion',
    about: 'Unser Unternehmen',
    contact: 'Kontakt',
    details: 'Produkt ansehen',
    inquire: 'Zu diesem Produkt anfragen',
    material: 'Material',
    dimensions: 'Abmessungen',
    name: 'Ihr Name',
    email: 'E-Mail-Adresse',
    company: 'Unternehmen',
    message: 'Ihre Nachricht',
    send: 'Anfrage senden',
    sending: 'Wird gesendet…',
    sent: 'Ihre Anfrage wurde gespeichert. Vielen Dank.',
    failed: 'Ihre Anfrage konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.',
    preview: 'Private Vorschau · Anfragen sind deaktiviert',
    products: 'Unsere Produkte',
    discover: 'Kollektion entdecken',
    conversation: 'Kommen wir ins Gespräch.',
    contactIntro: 'Teilen Sie uns mit, wonach Sie suchen.',
    product: 'Produkt',
    optional: 'Optional',
    allProducts: 'Alle Produkte',
    trader: 'Handelsunternehmen',
    factory: 'Hersteller',
    back: 'Zurück zur Kollektion',
    pause: 'Video pausieren',
    play: 'Video abspielen',
    language: 'Sprache',
    skip: 'Zum Inhalt springen',
    unavailable: 'Bild folgt',
    noProducts: 'Produkte werden hier angezeigt.',
    related: 'Mehr entdecken',
    emailDirect: 'Oder schreiben Sie uns direkt',
    rights: 'Alle Rechte vorbehalten',
    menu: 'Navigation',
  },
  fr: {
    home: 'Accueil',
    catalog: 'Collection',
    about: 'Notre entreprise',
    contact: 'Contact',
    details: 'Voir le produit',
    inquire: 'Se renseigner sur ce produit',
    material: 'Matériau',
    dimensions: 'Dimensions',
    name: 'Votre nom',
    email: 'Adresse e-mail',
    company: 'Entreprise',
    message: 'Votre message',
    send: 'Envoyer une demande',
    sending: 'Envoi en cours…',
    sent: 'Votre demande a été enregistrée. Merci.',
    failed: 'Impossible d’enregistrer votre demande. Veuillez réessayer.',
    preview: 'Aperçu privé · envoi de demandes désactivé',
    products: 'Nos produits',
    discover: 'Découvrir la collection',
    conversation: 'Parlons de votre projet.',
    contactIntro: 'Dites-nous ce que vous recherchez.',
    product: 'Produit',
    optional: 'Facultatif',
    allProducts: 'Tous les produits',
    trader: 'Société de négoce',
    factory: 'Fabricant',
    back: 'Retour à la collection',
    pause: 'Mettre la vidéo en pause',
    play: 'Lire la vidéo',
    language: 'Langue',
    skip: 'Aller au contenu',
    unavailable: 'Image à venir',
    noProducts: 'Les produits apparaîtront ici.',
    related: 'À découvrir aussi',
    emailDirect: 'Ou écrivez-nous directement',
    rights: 'Tous droits réservés',
    menu: 'Navigation',
  },
  es: {
    home: 'Inicio',
    catalog: 'Colección',
    about: 'Nuestra empresa',
    contact: 'Contacto',
    details: 'Ver producto',
    inquire: 'Consultar sobre este producto',
    material: 'Material',
    dimensions: 'Dimensiones',
    name: 'Su nombre',
    email: 'Correo electrónico',
    company: 'Empresa',
    message: 'Su mensaje',
    send: 'Enviar consulta',
    sending: 'Enviando…',
    sent: 'Su consulta se ha guardado. Gracias.',
    failed: 'No se pudo guardar su consulta. Inténtelo de nuevo.',
    preview: 'Vista previa privada · envío de consultas desactivado',
    products: 'Nuestros productos',
    discover: 'Descubrir la colección',
    conversation: 'Hablemos de su proyecto.',
    contactIntro: 'Cuéntenos qué está buscando.',
    product: 'Producto',
    optional: 'Opcional',
    allProducts: 'Todos los productos',
    trader: 'Empresa comercial',
    factory: 'Fabricante',
    back: 'Volver a la colección',
    pause: 'Pausar vídeo',
    play: 'Reproducir vídeo',
    language: 'Idioma',
    skip: 'Ir al contenido',
    unavailable: 'Imagen próximamente',
    noProducts: 'Los productos aparecerán aquí.',
    related: 'Más para descubrir',
    emailDirect: 'O escríbanos directamente',
    rights: 'Todos los derechos reservados',
    menu: 'Navegación',
  },
  pt: {
    home: 'Início',
    catalog: 'Coleção',
    about: 'A nossa empresa',
    contact: 'Contacto',
    details: 'Ver produto',
    inquire: 'Consultar sobre este produto',
    material: 'Material',
    dimensions: 'Dimensões',
    name: 'O seu nome',
    email: 'Endereço de e-mail',
    company: 'Empresa',
    message: 'A sua mensagem',
    send: 'Enviar consulta',
    sending: 'A enviar…',
    sent: 'A sua consulta foi guardada. Obrigado.',
    failed: 'Não foi possível guardar a sua consulta. Tente novamente.',
    preview: 'Pré-visualização privada · envio de consultas desativado',
    products: 'Os nossos produtos',
    discover: 'Descobrir a coleção',
    conversation: 'Vamos conversar.',
    contactIntro: 'Diga-nos o que procura.',
    product: 'Produto',
    optional: 'Opcional',
    allProducts: 'Todos os produtos',
    trader: 'Empresa comercial',
    factory: 'Fabricante',
    back: 'Voltar à coleção',
    pause: 'Pausar vídeo',
    play: 'Reproduzir vídeo',
    language: 'Idioma',
    skip: 'Saltar para o conteúdo',
    unavailable: 'Imagem em breve',
    noProducts: 'Os produtos aparecerão aqui.',
    related: 'Mais para descobrir',
    emailDirect: 'Ou envie-nos um e-mail',
    rights: 'Todos os direitos reservados',
    menu: 'Navegação',
  },
  it: {
    home: 'Home',
    catalog: 'Collezione',
    about: 'La nostra azienda',
    contact: 'Contatti',
    details: 'Vedi prodotto',
    inquire: 'Richiedi informazioni sul prodotto',
    material: 'Materiale',
    dimensions: 'Dimensioni',
    name: 'Il suo nome',
    email: 'Indirizzo e-mail',
    company: 'Azienda',
    message: 'Il suo messaggio',
    send: 'Invia richiesta',
    sending: 'Invio in corso…',
    sent: 'La sua richiesta è stata salvata. Grazie.',
    failed: 'Impossibile salvare la richiesta. Riprovi.',
    preview: 'Anteprima privata · invio richieste disattivato',
    products: 'I nostri prodotti',
    discover: 'Scopri la collezione',
    conversation: 'Parliamo del suo progetto.',
    contactIntro: 'Ci racconti cosa sta cercando.',
    product: 'Prodotto',
    optional: 'Facoltativo',
    allProducts: 'Tutti i prodotti',
    trader: 'Società commerciale',
    factory: 'Produttore',
    back: 'Torna alla collezione',
    pause: 'Metti in pausa il video',
    play: 'Riproduci video',
    language: 'Lingua',
    skip: 'Vai al contenuto',
    unavailable: 'Immagine in arrivo',
    noProducts: 'I prodotti appariranno qui.',
    related: 'Altro da scoprire',
    emailDirect: 'Oppure ci scriva direttamente',
    rights: 'Tutti i diritti riservati',
    menu: 'Navigazione',
  },
} satisfies Record<Language, Record<string, string>>;
