import { isProductNativeEnhancedRevision } from '../../../shared/product-native-materials';
import type { Draft, Product } from '../../../shared/model';
import { displayProducts } from '../../../shared/product-display';
import { materialImage } from '../../materials-render';
import { toorunStyles } from '../toorunStyles';
import { buildThemeContext, esc, productPath, type RenderOptions } from '../types';
import { toorunProductMaterialsRevision } from './product-materials';
import { renderProductGallery } from '../../product-native-gallery';

const lines = (value: string) => value.split(/\r?\n/).map(line => line.trim()).filter(Boolean);
const multiline = (value: string) => esc(value).replace(/\r?\n/g, '<br>');
const brandMark = '<span class="tr-brand-mark" aria-hidden="true"><i></i><i></i><i></i></span>';

/** Product-only native layout. The original Toorun renderer and CSS remain frozen. */
export function renderToorunProductSite(draft: Draft, options: RenderOptions): string {
  const enhanced = isProductNativeEnhancedRevision('toorun-early-learning', draft.materials?.contractRevision);
  const materials = draft.materials;
  if (!materials || (materials.contractRevision !== toorunProductMaterialsRevision && !enhanced)) throw new Error('Toorun product materials revision required');
  const products = displayProducts(draft);
  const canonicalId = (id?: string) => id && (products.some(product => product.id === id) ? id : draft.productDisplayGroups?.find(group => group.includes(id))?.[0] || id);
  const ctx = buildThemeContext({ ...draft, products }, { ...options, productId: canonicalId(options.productId) });
  const { page, lang, path, navPath, navAttrs, ui, translateProduct } = ctx;
  const text = (id: string) => materials.textBindings.find(binding => binding.slotId === id && binding.locale === lang)?.text || '';
  const mark = (id: string) => `data-wr-material-text="${esc(id)}"`;
  const route = (target: string, label: string, cls = '', productId?: string, slotId?: string) => `<a class="${esc(cls)}" href="${esc(path(target === 'detail' ? productPath(productId) : navPath(target)) + (target === 'contact' && productId ? `?productId=${encodeURIComponent(canonicalId(productId)!)}` : ''))}" ${navAttrs(target, productId)}${page === target ? ' aria-current="page"' : ''}${slotId ? ` ${mark(slotId)}` : ''}>${label}</a>`;
  const button = (target = 'contact', slotId = 'enquiry-cta', productId?: string) => route(target, `<span>${esc(text(slotId))}</span><span class="tr-button-arrow" aria-hidden="true">↗</span>`, 'tr-button', productId, slotId);
  const photo = (slotId: string, productId?: string, eager = false, cls = '') => {
    const binding = materials.imageBindings.find(binding => binding.slotId === slotId && (!productId || binding.productId === productId));
    if (!binding) throw new Error(`Missing validated Toorun image ${slotId}:${productId || ''}`);
    const image = materialImage(binding, { ...options, lang }).replace('<img ', `<img class="${esc(cls)}" data-wr-material-image="${esc(slotId)}"${binding.productId ? ` data-wr-material-product="${esc(binding.productId)}"` : ''} `);
    return eager ? image.replace('loading="lazy"', 'loading="eager" fetchpriority="high"') : image;
  };
  const scenes = (materials.displaySelection?.sceneProductIds || []).map(id => draft.products.find(product => product.id === id)).filter((product): product is Product => !!product);
  const contextScenes = [...scenes.map((product, i) => ({ slotId: 'context-scene', productId: product.id, position: i + 1 })), ...[4, 5].map(position => ({ slotId: `context-scene-${position}`, productId: undefined, position }))];
  const sceneProduct = (slotId: string, productId?: string) => draft.products.find(product => product.id === materials.imageBindings.find(binding => binding.slotId === slotId && (!productId || binding.productId === productId))?.productId);
  const sceneCaption = (slotId: string, productId?: string) => {
    const product = sceneProduct(slotId, productId);
    return product ? `<figcaption>${route('detail', esc(translateProduct(product).name), '', canonicalId(product.id))}</figcaption>` : '';
  };
  const heading = (region: string) => `<div class="tr-section-heading"><span class="tr-label" ${mark(`${region}-eyebrow`)}>${esc(text(`${region}-eyebrow`))}</span><h2 ${mark(`${region}-headline`)}>${multiline(text(`${region}-headline`))}</h2><p ${mark(`${region}-description`)}>${esc(text(`${region}-description`))}</p></div>`;
  const pageHeading = (region: 'catalog' | 'about' | 'contact') => `<section class="tr-page-hero" data-wr-hero data-wr-material-region="${region}-heading"><span class="tr-label" ${mark(`${region}-eyebrow`)}>${esc(text(`${region}-eyebrow`))}</span><h1 ${mark(`${region}-headline`)}>${multiline(text(`${region}-headline`))}</h1><p ${mark(`${region}-description`)}>${esc(text(`${region}-description`))}</p></section>`;
  const featuredIds = materials.displaySelection?.featuredProductIds || [];
  const featured = products.filter(product => featuredIds.some(id => canonicalId(id) === product.id));
  const cards = (items: Product[]) => `<div class="tr-program-grid" data-wr-product-list="${page}" data-product-count="${items.length}">${items.map((product, index) => `<article class="tr-program-card" data-wr-product-card data-wr-product-id="${esc(product.id)}"><span class="tr-program-index">${String(index + 1).padStart(2, '0')}</span>${route('detail', photo('product-main', product.id), 'tr-product-image', product.id)}<div class="tr-program-copy"><h3>${esc(translateProduct(product).name)}</h3>${product.tagline ? `<p>${esc(product.tagline)}</p>` : ''}${product.dimensions ? `<span class="tr-chip">${esc(product.dimensions)}</span>` : ''}</div>${route('detail', `${esc(ui.details)} ↗`, 'tr-text-link', product.id)}</article>`).join('')}</div>`;
  const values = () => `<section class="tr-section tr-values" data-wr-material-region="product-observations">${[1, 2, 3].map(i => `<article><span>${String(i).padStart(2, '0')}</span><h3 ${mark(`value-${i}-title`)}>${esc(text(`value-${i}-title`))}</h3><p ${mark(`value-${i}-description`)}>${esc(text(`value-${i}-description`))}</p></article>`).join('')}</section>`;
  const process = () => `<section class="tr-section tr-process" data-wr-material-region="enquiry-steps"><div>${heading('process')}</div><div class="tr-process-grid">${[1, 2, 3].map(i => `<article><span>${String(i).padStart(2, '0')}</span><h3 ${mark(`process-${i}-title`)}>${esc(text(`process-${i}-title`))}</h3><p ${mark(`process-${i}-description`)}>${esc(text(`process-${i}-description`))}</p></article>`).join('')}</div></section>`;
  const faq = () => `<section class="tr-section tr-faq" data-wr-material-region="faq"><div>${heading('faq')}${route('contact', `${esc(ui.contact)} ↗`, 'tr-text-link')}</div><div class="tr-faq-list">${[1, 2, 3, 4].map(i => `<details><summary ${mark(`faq-question-${i}`)}>${esc(text(`faq-question-${i}`))}<span aria-hidden="true">+</span></summary><p ${mark(`faq-answer-${i}`)}>${esc(text(`faq-answer-${i}`))}</p></details>`).join('')}</div></section>`;
  const points = (id: string) => `<ul ${mark(id)}>${lines(text(id)).map(point => `<li>${esc(point)}</li>`).join('')}</ul>`;
  let body = '';
  if (page === 'home') body = `<section class="tr-hero" data-wr-hero data-wr-material-region="hero"><div class="tr-hero-content wr-confirmed-hero-copy"><span class="tr-label" ${mark('hero-eyebrow')}>${esc(text('hero-eyebrow'))}</span><h1 ${mark('hero-headline')}>${multiline(text('hero-headline'))}</h1><p ${mark('hero-description')}>${esc(text('hero-description'))}</p>${button('catalog', 'primary-cta')}</div><div class="tr-hero-portraits">${scenes.map(product => `<figure class="tr-portrait">${photo('hero-scene', product.id, true, 'tr-hero-image')}</figure>`).join('')}<figure class="tr-portrait">${photo('hero-scene-4', undefined, true, 'tr-hero-image')}</figure></div></section><section class="tr-section tr-intro" data-wr-material-region="introduction"><div class="tr-section-heading"><span class="tr-label" ${mark('intro-eyebrow')}>${esc(text('intro-eyebrow'))}</span><h2 ${mark('intro-headline')}>${multiline(text('intro-headline'))}</h2></div><div><p ${mark('intro-description')}>${esc(text('intro-description'))}</p>${route('about', `${esc(lang === 'en' ? 'About us' : ui.about)} ↗`, 'tr-text-link')}</div></section>${values()}<section class="tr-photo-section" data-wr-material-region="product-context"><div class="tr-photo-copy">${heading('context')}${points('context-points')}${button('catalog', 'primary-cta')}</div><div class="tr-collage-group"><div class="tr-collage" data-scene-count="${scenes.length}">${contextScenes.map((scene, i) => `<figure class="tr-collage-${scene.position}" aria-describedby="tr-context-caption-${i}">${photo(scene.slotId, scene.productId)}<span class="tr-collage-marker" aria-hidden="true">${String(i + 1).padStart(2, '0')}</span></figure>`).join('')}</div><ol class="tr-collage-captions">${contextScenes.map((scene, i) => { const product = sceneProduct(scene.slotId, scene.productId)!; return `<li id="tr-context-caption-${i}"><span aria-hidden="true">${String(i + 1).padStart(2, '0')}</span>${route('detail', `${esc(translateProduct(product).name)} ↗`, '', canonicalId(product.id))}</li>`; }).join('')}</ol></div></section><section class="tr-section tr-programs" data-wr-material-region="collection">${heading('catalog')}${cards(featured)}${featured.length < products.length ? route('catalog', `${esc(ui.catalog)} ↗`, 'tr-text-link') : ''}</section>${process()}${faq()}`;
  if (page === 'catalog') body = `${pageHeading('catalog')}<section class="tr-section tr-programs tr-programs-page" data-wr-material-region="collection">${cards(products)}</section>${process()}${faq()}`;
  if (page === 'detail') {
    const product = products.find(product => product.id === canonicalId(options.productId));
    body = product ? `<section class="tr-section tr-detail" data-wr-hero data-wr-material-region="detail">${renderProductGallery(draft, options, product, `<div class="tr-detail-media">${photo('product-main', product.id, true).replace('<img ', '<img id="wr-detail-main-img" ')}</div>`)}<div class="tr-detail-copy">${route('catalog', `← ${esc(ui.back)}`, 'tr-text-link')}<h1>${esc(translateProduct(product).name)}</h1>${product.tagline ? `<p class="tr-label">${esc(product.tagline)}</p>` : ''}<p>${esc(translateProduct(product).description)}</p>${product.sellingPoints?.length ? `<ul class="tr-check-list">${product.sellingPoints.map(point => `<li>${esc(point)}</li>`).join('')}</ul>` : ''}<dl>${product.material ? `<div><dt>${esc(ui.material)}</dt><dd>${esc(product.material)}</dd></div>` : ''}${product.dimensions ? `<div><dt>${esc(ui.dimensions)}</dt><dd>${esc(product.dimensions)}</dd></div>` : ''}</dl>${button('contact', 'enquiry-cta', product.id)}</div></section>${process()}` : `<section class="tr-section"><h1>${esc(ui.noProducts)}</h1>${route('catalog', esc(ui.catalog), 'tr-text-link')}</section>`;
  }
  if (page === 'about') body = `${pageHeading('about')}<section class="tr-section tr-about-lead" data-wr-material-region="about-story"><div class="tr-about-image">${photo('about-primary-image', undefined, true, 'tr-about-main')}</div><div><div ${mark('about-story')}>${lines(text('about-story')).map(paragraph => `<p>${esc(paragraph)}</p>`).join('')}</div>${text('company-about') ? `<p ${mark('company-about')}>${esc(text('company-about'))}</p>` : ''}${draft.company.capabilities ? `<p>${esc(draft.company.capabilities)}</p>` : ''}${draft.company.certifications ? `<p>${esc(draft.company.certifications)}</p>` : ''}</div></section>${values()}<section class="tr-photo-section tr-product-design" data-wr-material-region="about-design"><div class="tr-photo-copy">${heading('about-context')}${points('about-context-points')}${button('catalog', 'primary-cta')}</div><div class="tr-design-frames"><figure>${photo('about-scene-1')}${sceneCaption('about-scene-1')}</figure><figure>${photo('about-scene-2')}${sceneCaption('about-scene-2')}</figure></div></section>${faq()}`;
  if (page === 'contact') body = `${pageHeading('contact')}<section class="tr-section tr-contact" data-wr-material-region="contact"><aside><span class="tr-label">${esc(ui.contact)}</span><h2>${esc(draft.company.name)}</h2>${draft.company.contactName ? `<p>${esc(draft.company.contactName)}</p>` : ''}${draft.company.email ? `<a href="mailto:${esc(draft.company.email)}">${esc(draft.company.email)}</a>` : ''}${draft.company.phone ? `<a href="tel:${esc(draft.company.phone.replace(/[^+\d]/g, ''))}">${esc(draft.company.phone)}</a>` : ''}${draft.company.address ? `<p>${esc(draft.company.address)}</p>` : ''}${ctx.socials ? `<div class="tr-socials">${ctx.socials}</div>` : ''}</aside><div class="tr-form-wrap"><h2 ${mark('contact-form-headline')}>${esc(text('contact-form-headline'))}</h2><p ${mark('contact-form-description')}>${esc(text('contact-form-description'))}</p>${ctx.inquiryFormHtml}</div></section>${process()}`;
  const logo = draft.company.logoAssetId ? ctx.brandLogo : `${brandMark}<strong>${esc(draft.company.name)}</strong>`;
  const nav = `${enhanced ? route('home', esc(ui.home)) : ''}${route('catalog', esc(ui.catalog))}${route('about', esc(lang === 'en' ? 'About us' : ui.about))}`;
  const header = `<a class="tr-skip" href="#main">${esc(ui.skip)}</a><header class="tr-header"${enhanced ? ' data-wr-nav-layout="playful-centered"' : ''}><div class="tr-nav">${route('home', logo, 'tr-brand')}<details class="tr-menu"${enhanced ? ' data-product-nav-disclosure' : ''}><summary aria-label="${esc(ui.menu)}"><span></span><span></span><span></span></summary><nav>${nav}${button()}${draft.languages.length > 1 ? ctx.languageLinks : ''}</nav></details><nav class="tr-desktop-nav" aria-label="${esc(ui.menu)}">${nav}</nav>${button()}${draft.languages.length > 1 ? `<div class="tr-languages">${ctx.languageLinks}</div>` : ''}</div></header>`;
  const footer = `<footer class="tr-footer"><div class="tr-footer-cloud" data-wr-material-region="closing-enquiry"><div>${route('home', logo, 'tr-brand tr-footer-brand')}<h2 ${mark('footer-headline')}>${multiline(text('footer-headline'))}</h2><p ${mark('footer-description')}>${esc(text('footer-description'))}</p>${button()}</div></div><div class="tr-footer-bottom"><div><strong>${esc(draft.company.name)}</strong>${draft.company.description ? `<p>${esc(draft.company.description)}</p>` : ''}</div><nav>${nav}${route('contact', esc(ui.contact))}</nav><div>${draft.company.email ? `<a href="mailto:${esc(draft.company.email)}">${esc(draft.company.email)}</a>` : ''}${ctx.socials}</div></div><div class="tr-legal">© ${new Date().getUTCFullYear()} ${esc(draft.company.name)} · ${esc(ui.rights)}</div></footer>`;
  const palette = materials.visual.palette;
  const color = (value: string, fallback: string) => /^#[a-f\d]{6}$/i.test(value) ? value : fallback;
  const variables = `--tr-green:${color(palette.primary, '#3f6b52')};--tr-yellow:${color(palette.secondary, '#f6c84c')};--tr-cream:${color(palette.background, '#fbf7ee')};--tr-lime:${color(palette.surface, '#d9ea8e')};--tr-ink:${color(palette.text, '#17251f')};`;
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(text(`${page}-seo-title`) || draft.company.name)}</title><meta name="description" content="${esc(text(`${page}-seo-description`))}">${options.preview ? '<meta name="robots" content="noindex,nofollow">' : ''}<style>${toorunStyles}\n${productStyles}${enhanced ? toorunEnhancedNavigation : ''}</style></head><body class="toorun-early-learning wr-toorun-products" data-template="toorun-early-learning" data-wr-materials-revision="${esc(materials.contractRevision)}" style="${variables}">${header}<main id="main">${body}</main>${footer}</body></html>`;
}

const toorunEnhancedNavigation = `
.wr-toorun-products .tr-nav{display:grid;grid-template-columns:1fr auto 1fr;height:96px;gap:24px}.wr-toorun-products .tr-nav>.tr-brand{grid-column:2;grid-row:1;justify-content:center;font-size:28px}.wr-toorun-products .tr-desktop-nav{grid-column:1;grid-row:1;justify-content:flex-start;margin-left:0;gap:22px}.wr-toorun-products .tr-nav>.tr-button{grid-column:3;grid-row:1;justify-self:end}.wr-toorun-products .tr-nav>.tr-languages{grid-column:1/-1;justify-content:center}.wr-toorun-products .tr-desktop-nav a[aria-current=page]:after{height:7px;bottom:0;border-radius:40%;opacity:.3;transform:rotate(-3deg)}
@media(max-width:991px){.wr-toorun-products .tr-nav{height:80px;grid-template-columns:1fr auto 1fr;gap:12px}.wr-toorun-products .tr-nav>.tr-brand{font-size:23px}.wr-toorun-products .tr-menu{display:block;grid-column:3;grid-row:1;justify-self:end;margin:0}.wr-toorun-products .tr-menu summary{background:var(--tr-yellow);transform:rotate(4deg)}.wr-toorun-products .tr-menu summary span{background:var(--tr-ink)}.wr-toorun-products .tr-nav>.tr-button,.wr-toorun-products .tr-desktop-nav{display:none}.wr-toorun-products .tr-nav>.tr-languages{display:none}}
@media(max-width:480px){.wr-toorun-products .tr-nav{grid-template-columns:1fr auto}.wr-toorun-products .tr-nav>.tr-brand{grid-column:1;justify-content:flex-start;max-width:280px;font-size:22px}.wr-toorun-products .tr-menu{grid-column:2}}
`;

const productStyles = `
.wr-toorun-products :is(h1,h2,h3,p,a,li,dd){overflow-wrap:anywhere}.wr-toorun-products :is(.tr-intro,.tr-detail,.tr-about-lead,.tr-contact,.tr-program-grid)>*{min-width:0}.wr-toorun-products figure{margin:0}
.wr-toorun-products .tr-skip{position:fixed;top:-100px;left:16px;padding:12px 18px;background:white;z-index:100}.wr-toorun-products .tr-skip:not(:focus){clip-path:inset(50%)}.wr-toorun-products .tr-skip:focus{top:12px}.wr-toorun-products .tr-brand img{width:auto;max-width:180px;max-height:54px;object-fit:contain}
.wr-toorun-products .tr-hero-image{filter:none}.wr-toorun-products .tr-portrait picture{display:block;width:100%;height:100%}.wr-toorun-products .tr-hero-portraits figure{margin:0 -20px}.wr-toorun-products .tr-portrait:hover .tr-hero-image{filter:none}
.wr-toorun-products .tr-program-card{justify-content:flex-start;padding:28px}.wr-toorun-products .tr-program-copy{margin-top:0}.wr-toorun-products .tr-product-image{display:block;background:#fff;border-radius:24px;margin:20px 0 0;overflow:hidden}.wr-toorun-products .tr-product-image :is(img,picture){display:block;width:100%}.wr-toorun-products .tr-product-image img{aspect-ratio:1;height:auto;object-fit:contain}.wr-toorun-products .tr-program-card>.tr-text-link{margin-top:auto;padding-top:22px}.wr-toorun-products .tr-program-grid[data-product-count="1"]{grid-template-columns:minmax(0,420px);justify-content:center}.wr-toorun-products .tr-program-grid[data-product-count="2"]{grid-template-columns:repeat(2,minmax(0,1fr));max-width:900px;margin:auto}
.wr-toorun-products .tr-photo-section{background-image:linear-gradient(#244633de,#244633de),url('/templates/toorun-early-learning/footer-clouds.jpg')}.wr-toorun-products .tr-photo-copy :is(h2,p){color:inherit}.wr-toorun-products .tr-photo-copy .tr-section-heading p{opacity:.88}.wr-toorun-products .tr-collage picture{display:block;height:100%}.wr-toorun-products .tr-collage img{height:100%}.wr-toorun-products .tr-collage-group{min-width:0}.wr-toorun-products .tr-collage-marker{position:absolute;top:12px;left:12px;display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:var(--tr-yellow);color:var(--tr-ink);font-size:12px;font-weight:700}.wr-toorun-products .tr-collage-3 .tr-collage-marker{left:auto;right:12px}.wr-toorun-products .tr-collage-captions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px 24px;padding:0;margin:30px 0 0;list-style:none}.wr-toorun-products .tr-collage-captions li{display:flex;align-items:baseline;gap:10px;min-width:0;font-size:13px;line-height:1.5}.wr-toorun-products .tr-collage-captions li>span{flex-shrink:0;color:var(--tr-yellow);font-weight:700}.wr-toorun-products .tr-collage-captions a{min-width:0;text-decoration:underline;text-underline-offset:3px}.wr-toorun-products .tr-collage-captions a:focus-visible{outline:2px solid var(--tr-yellow);outline-offset:4px}
.wr-toorun-products .tr-collage[data-scene-count="1"] .tr-collage-1{width:58%;height:75%;left:0;top:0}.wr-toorun-products .tr-collage[data-scene-count="1"] .tr-collage-4{width:42%;height:46%;left:auto;right:0;top:0;bottom:auto}.wr-toorun-products .tr-collage[data-scene-count="1"] .tr-collage-5{width:46%;height:48%;right:5%;bottom:0}.wr-toorun-products .tr-collage[data-scene-count="2"] .tr-collage-2{left:auto;right:0;width:48%}
.wr-toorun-products .tr-design-frames{display:grid;grid-template-columns:1.1fr .9fr;gap:22px;align-items:center;padding:10px}.wr-toorun-products .tr-design-frames figure{min-width:0;background:white;border:8px solid white;border-radius:28px;overflow:hidden;transform:rotate(-4deg);box-shadow:0 18px 45px #0002}.wr-toorun-products .tr-design-frames figure:nth-child(2){transform:rotate(5deg) translateY(45px)}.wr-toorun-products .tr-design-frames :is(img,picture){display:block;width:100%}.wr-toorun-products .tr-design-frames img{aspect-ratio:5/7;height:auto;object-fit:cover}.wr-toorun-products .tr-design-frames figure:nth-child(2) img{aspect-ratio:1}.wr-toorun-products .tr-design-frames figcaption{padding:14px;color:var(--tr-ink);font-size:13px}
.wr-toorun-products .tr-about-image :is(img,picture){display:block;width:100%;position:relative}.wr-toorun-products .tr-about-main{height:auto;aspect-ratio:20/21}.wr-toorun-products .tr-detail-media :is(img,picture){display:block;width:100%}.wr-toorun-products .tr-detail-media img{aspect-ratio:1;object-fit:contain;background:white;border-radius:36px}.wr-toorun-products .tr-detail-copy>.tr-label{display:block;line-height:1.5}.wr-toorun-products .tr-footer-cloud{color:var(--tr-ink)}.wr-toorun-products .tr-footer-cloud p{color:var(--tr-ink);margin-bottom:26px}.wr-toorun-products .tr-contact aside h2{font-size:36px}
@media(max-width:600px){.wr-toorun-products .tr-hero{padding-bottom:60px;min-height:0}.wr-toorun-products .tr-hero-portraits{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));width:90%;height:auto;gap:12px;margin-top:45px}.wr-toorun-products .tr-hero-portraits .tr-portrait{display:block;width:100%;height:220px;margin:0;border-width:6px;transform:rotate(-5deg)}.wr-toorun-products .tr-hero-portraits .tr-portrait:nth-child(even){transform:rotate(5deg) translateY(14px)}.wr-toorun-products .tr-program-grid[data-product-count="2"]{grid-template-columns:1fr}.wr-toorun-products .tr-collage-3{display:block;width:30%;height:34%;right:0;top:29%;z-index:2}.wr-toorun-products .tr-collage-marker{top:8px;left:8px;width:26px;height:26px;font-size:11px}.wr-toorun-products .tr-collage-3 .tr-collage-marker{left:auto;right:8px}.wr-toorun-products .tr-collage-captions{grid-template-columns:1fr;margin-top:24px}.wr-toorun-products .tr-design-frames{gap:12px;padding:0 8px 40px}.wr-toorun-products .tr-design-frames figure{border-width:5px;border-radius:20px}.wr-toorun-products .tr-design-frames figcaption{padding:8px;font-size:11px}.wr-toorun-products .tr-nav>.tr-languages{display:none}}
`;
