import { isProductNativeEnhancedRevision } from '../../../shared/product-native-materials';
import type { Draft, Product } from '../../../shared/model';
import { displayProducts } from '../../../shared/product-display';
import { materialImage } from '../../materials-render';
import { melloStyles } from '../melloStyles';
import { buildThemeContext, esc, productPath, type RenderOptions } from '../types';
import { melloProductMaterialsRevision } from './product-materials';
import { renderProductGallery } from '../../product-native-gallery';

const lines = (value: string) => value.split(/\r?\n/).map(line => line.trim()).filter(Boolean);
const multiline = (value: string) => esc(value).replace(/\r?\n/g, '<br>');
const flower = '<span class="mp-flower" aria-hidden="true">✳</span>';

/** Product scenes in Mello's display type, editorial panels and perforated receipt. */
export function renderMelloProductSite(draft: Draft, options: RenderOptions): string {
  const enhanced = isProductNativeEnhancedRevision('mello-coffee', draft.materials?.contractRevision);
  const materials = draft.materials;
  if (!materials || (materials.contractRevision !== melloProductMaterialsRevision && !enhanced)) throw new Error('Mello product materials revision required');
  const products = displayProducts(draft);
  const canonicalId = (id?: string) => id && (products.some(product => product.id === id) ? id : draft.productDisplayGroups?.find(group => group.includes(id))?.[0] || id);
  const ctx = buildThemeContext({ ...draft, products }, { ...options, productId: canonicalId(options.productId) });
  const { page, lang, path, navPath, navAttrs, ui, translateProduct } = ctx;
  const text = (id: string, productId?: string) => materials.textBindings.find(binding => binding.slotId === id && binding.locale === lang && (!productId || binding.productId === productId))?.text || '';
  const mark = (id: string) => `data-wr-material-text="${esc(id)}"`;
  const route = (target: string, label: string, cls = '', productId?: string, slotId?: string) => `<a class="${esc(cls)}" href="${esc(path(target === 'detail' ? productPath(productId) : navPath(target)) + (target === 'contact' && productId ? `?productId=${encodeURIComponent(canonicalId(productId)!)}` : ''))}" ${navAttrs(target, productId)}${page === target ? ' aria-current="page"' : ''}${slotId ? ` ${mark(slotId)}` : ''}>${label}</a>`;
  const button = (target = 'contact', slotId = 'enquiry-cta', productId?: string) => route(target, `<span class="button-border"></span><span class="button-background"></span><span class="emphasis-l top-index">${esc(text(slotId))} ↗</span>`, 'button w-inline-block', productId, slotId);
  const photo = (slotId: string, productId?: string, eager = false, cls = '') => {
    const binding = materials.imageBindings.find(binding => binding.slotId === slotId && (!productId || binding.productId === productId));
    if (!binding) throw new Error(`Missing validated Mello image ${slotId}:${productId || ''}`);
    const image = materialImage(binding, { ...options, lang }).replace('<img ', `<img class="${esc(cls)}" data-wr-material-image="${esc(slotId)}"${binding.productId ? ` data-wr-material-product="${esc(binding.productId)}"` : ''} `);
    return eager ? image.replace('loading="lazy"', 'loading="eager" fetchpriority="high"') : image;
  };
  const sceneProduct = (slotId: string) => draft.products.find(product => product.id === materials.imageBindings.find(binding => binding.slotId === slotId)?.productId);
  const selected = (group: 'scene' | 'featured') => {
    const ids = materials.displaySelection?.[group === 'scene' ? 'sceneProductIds' : 'featuredProductIds'] || [];
    return ids.map(id => draft.products.find(product => product.id === (group === 'featured' ? canonicalId(id) : id))).filter((product): product is Product => !!product).filter((product, i, all) => all.findIndex(other => other.id === product.id) === i);
  };
  const heading = (region: string) => `<div class="section-heading"><div class="heading-title"><div class="label"><span class="circle"></span><span class="handwritten-l" ${mark(`${region}-eyebrow`)}>${esc(text(`${region}-eyebrow`))}</span></div><h2 class="h2 heading-h2" ${mark(`${region}-headline`)}>${multiline(text(`${region}-headline`))}</h2></div><div class="text-wrapper"><p class="body-l secton-description" ${mark(`${region}-description`)}>${esc(text(`${region}-description`))}</p></div></div>`;
  const pageHeading = (region: 'catalog' | 'about' | 'contact') => `<section class="section top-padd mp-page-heading" data-wr-hero data-wr-material-region="${region}-heading"><div class="container"><div class="label"><span class="circle"></span><span class="handwritten-l" ${mark(`${region}-eyebrow`)}>${esc(text(`${region}-eyebrow`))}</span></div><h1 class="h1 hero-h1" ${mark(`${region}-headline`)}>${multiline(text(`${region}-headline`))}</h1><p class="body-l" ${mark(`${region}-description`)}>${esc(text(`${region}-description`))}</p></div></section>`;
  const ticker = () => `<div class="ticker mp-ticker" aria-hidden="true"><div class="ticker-line">${selected('scene').map(product => `<span class="display-s">${esc(translateProduct(product).name)}</span>${flower}`).join('')}</div></div>`;
  const specList = (items: Product[]) => `<section class="section both-padd" data-wr-material-region="specifications"><div class="container">${heading('comparison')}<div class="menu-info mp-spec-list">${items.map((product, index) => `<article class="menu-item" data-wr-product-id="${esc(product.id)}"><div><span class="handwritten-s">${String(index + 1).padStart(2, '0')}</span><h3 class="h3 h3-small">${route('detail', esc(translateProduct(product).name), '', product.id)}</h3>${product.tagline ? `<p class="body-m">${esc(product.tagline)}</p>` : ''}</div><div><span class="handwritten-s">${esc(ui.material)}</span><p class="body-m">${esc(product.material || '—')}</p></div><div><span class="handwritten-s">${esc(ui.dimensions)}</span><p class="body-m">${esc(product.dimensions || '—')}</p></div></article>`).join('')}</div>${items.length < products.length ? button('catalog', 'primary-cta') : ''}</div></section>`;
  const receipt = () => `<section class="section both-padd black" data-wr-material-region="product-facts"><div class="container"><div class="philosophy-content"><div class="philosophy-info"><div class="title-and-text-wrapper"><div class="label"><span class="circle"></span><span class="handwritten-l" ${mark('philosophy-eyebrow')}>${esc(text('philosophy-eyebrow'))}</span></div><h2 class="h2 heading-h2" ${mark('philosophy-headline')}>${multiline(text('philosophy-headline'))}</h2><p class="body-l" ${mark('philosophy-description')}>${esc(text('philosophy-description'))}</p></div>${button('catalog', 'primary-cta')}</div><div class="receipt-wrapper"><div class="receipt"><div class="receipt-circles top">${'<span class="receipt-circle"></span>'.repeat(16)}</div><div class="receipt-circles bottom">${'<span class="receipt-circle"></span>'.repeat(16)}</div><div class="receipt-info"><div class="receipt-header"><div class="logo-text"><span class="logo-font">${esc(draft.company.name)}</span><span class="handwritten-s" ${mark('receipt-title')}>${esc(text('receipt-title'))}</span></div>${flower}</div><div class="divider-border"></div><div class="receipt-items">${selected('scene').map(product => `<div class="receipt-item" data-wr-product-id="${esc(product.id)}"><span class="body-m">${esc(translateProduct(product).name)}</span><span class="emphasis-m">${esc(product.material || product.dimensions || product.tagline || '—')}</span></div>`).join('')}</div><div class="divider-border"></div><p class="handwritten-l" ${mark('receipt-note')}>${esc(text('receipt-note'))}</p></div><div class="mp-receipt-bars" aria-hidden="true"></div></div></div></div></div></section>`;
  const contexts = () => `<section class="section both-padd" data-wr-material-region="contexts"><div class="container">${heading('context')}<div class="spot mp-product-tabs" data-wr-product-tabs><div class="mp-panels">${selected('scene').map((product, i) => `<section id="mello-scene-${i}" data-wr-product-panel="${i}" data-wr-product-id="${esc(product.id)}"><div class="spot-content"><div class="spot-image">${photo('context-scene', product.id, false, 'image background-image')}</div><div class="spot-info"><div class="spot-details"><span class="handwritten-s">${String(i + 1).padStart(2, '0')} / ${String(selected('scene').length).padStart(2, '0')}</span><div class="block-text-wrapper"><h3 class="h3 block-title">${esc(translateProduct(product).name)}</h3><p class="body-m" ${mark('context-caption')} data-wr-material-product="${esc(product.id)}">${esc(text('context-caption', product.id))}</p></div>${route('detail', `${esc(ui.details)} ↗`, 'emphasis-l', canonicalId(product.id))}</div></div></div></section>`).join('')}</div><nav class="spot-tabs" aria-label="${esc(text('context-headline'))}">${selected('scene').map((product, i) => `<button class="spot-tab" type="button" data-wr-product-tab="${i}"><span class="handwritten-s">${String(i + 1).padStart(2, '0')}</span><span class="display-s">${esc(translateProduct(product).name)}</span></button>`).join('')}</nav></div></div></section>`;
  const collection = (items: Product[]) => `<div class="mp-catalog" data-wr-product-list="${page}" data-product-count="${items.length}">${items.map(product => `<article class="mello-card" data-wr-product-card data-wr-product-id="${esc(product.id)}">${route('detail', photo('product-main', product.id), 'mp-main-image', product.id)}<div class="mp-card-copy"><h2 class="h3 h3-small">${esc(translateProduct(product).name)}</h2><p class="body-m" ${mark('context-caption')} data-wr-material-product="${esc(product.id)}">${esc(text('context-caption', product.id))}</p>${product.dimensions ? `<p class="handwritten-s">${esc(product.dimensions)}</p>` : ''}${route('detail', `${esc(ui.details)} ↗`, 'emphasis-l', product.id)}</div></article>`).join('')}</div>`;
  const contactDetails = () => `<div class="mp-contact-details"><h3 class="h3 h3-small">${esc(draft.company.name)}</h3>${draft.company.contactName ? `<p class="body-m">${esc(draft.company.contactName)}</p>` : ''}${draft.company.email ? `<a href="mailto:${esc(draft.company.email)}">${esc(draft.company.email)}</a>` : ''}${draft.company.phone ? `<a href="tel:${esc(draft.company.phone.replace(/[^+\d]/g, ''))}">${esc(draft.company.phone)}</a>` : ''}${draft.company.address ? `<p class="body-m">${esc(draft.company.address)}</p>` : ''}</div>`;
  let body = '';
  if (page === 'home') {
    const heroProduct = sceneProduct('hero-scene');
    body = `<section class="hero" data-wr-hero data-wr-material-region="hero"><div class="container"><div class="hero-content"><div class="hero-text wr-confirmed-hero-copy"><span class="handwritten-l" ${mark('hero-eyebrow')}>${esc(text('hero-eyebrow'))}</span><h1 class="h1 hero-h1" ${mark('hero-headline')}>${multiline(text('hero-headline'))}</h1><p class="hero-p" ${mark('hero-description')}>${esc(text('hero-description'))}</p><div class="buttons-wrapper">${button('catalog', 'primary-cta')}${button()}</div></div><div class="hero-image mp-hero-image"><div class="mp-hero-caption">${heroProduct ? `<div class="product"><span class="display-s">${route('detail', esc(translateProduct(heroProduct).name), '', canonicalId(heroProduct.id))}</span>${heroProduct.tagline ? `<span class="body-m">${esc(heroProduct.tagline)}</span>` : ''}</div>` : ''}<div class="mp-hero-note">${flower}<span class="handwritten-l" ${mark('hero-note')}>${esc(text('hero-note'))}</span></div></div>${photo('hero-scene', undefined, true, 'image')}</div></div></div></section>${ticker()}<section class="section top-padd" data-wr-material-region="featured-scenes"><div class="container">${heading('featured')}<div class="menu-blocks mp-featured" data-wr-product-list="home" data-product-count="${selected('scene').length}">${selected('scene').map(product => `<article class="image-featured-menu-block-wrapper" data-wr-product-card data-wr-product-id="${esc(product.id)}"><div class="image-featured-menu-block">${photo('featured-scene', product.id, false, 'image bg-image')}<div class="linear"></div><div class="block-items-wrapper"><h3 class="h3 block-title">${route('detail', esc(translateProduct(product).name), '', canonicalId(product.id))}</h3>${product.tagline ? `<p class="body-m block-description">${esc(product.tagline)}</p>` : ''}${route('detail', `${esc(ui.details)} ↗`, 'emphasis-l', canonicalId(product.id))}</div></div></article>`).join('')}</div></div></section>${specList(selected('featured'))}${receipt()}${contexts()}<section class="section mp-editorial-note" data-wr-material-region="collection-note"><div class="container">${flower}<p class="display-m" ${mark('collection-note')}>${esc(text('collection-note'))}</p>${button('catalog', 'primary-cta')}</div></section>`;
  }
  if (page === 'catalog') body = `${pageHeading('catalog')}<section class="section mp-catalog-section" data-wr-material-region="collection"><div class="container">${collection(products)}</div></section>${specList(products)}`;
  if (page === 'detail') {
    const product = products.find(product => product.id === canonicalId(options.productId));
    body = product ? `<section class="section both-padd" data-wr-hero data-wr-material-region="detail"><div class="container mp-detail">${renderProductGallery(draft, options, product, `<div class="mp-detail-image">${photo('product-main', product.id, true).replace('<img ', '<img id="wr-detail-main-img" ')}</div>`)}<div>${route('catalog', `← ${esc(ui.back)}`, 'handwritten-l')}<h1 class="h1">${esc(translateProduct(product).name)}</h1>${product.tagline ? `<p class="handwritten-l">${esc(product.tagline)}</p>` : ''}<p class="body-l">${esc(translateProduct(product).description)}</p>${product.sellingPoints?.length ? `<ul class="mp-product-points">${product.sellingPoints.map(point => `<li>${esc(point)}</li>`).join('')}</ul>` : ''}<dl>${product.material ? `<div><dt>${esc(ui.material)}</dt><dd>${esc(product.material)}</dd></div>` : ''}${product.dimensions ? `<div><dt>${esc(ui.dimensions)}</dt><dd>${esc(product.dimensions)}</dd></div>` : ''}</dl>${button('contact', 'enquiry-cta', product.id)}</div></div></section>` : `<section class="section both-padd"><div class="container"><h1>${esc(ui.noProducts)}</h1>${route('catalog', esc(ui.catalog))}</div></section>`;
  }
  if (page === 'about') body = `${pageHeading('about')}<section class="section both-padd" data-wr-material-region="about-story"><div class="container mp-about-story"><figure>${photo('about-primary-image', undefined, true)}</figure><div><div ${mark('about-story')}>${lines(text('about-story')).map(paragraph => `<p class="body-l">${esc(paragraph)}</p>`).join('')}</div>${text('company-about') ? `<p class="body-m" ${mark('company-about')}>${esc(text('company-about'))}</p>` : ''}${draft.company.capabilities ? `<p class="body-m">${esc(draft.company.capabilities)}</p>` : ''}${draft.company.certifications ? `<p class="body-m">${esc(draft.company.certifications)}</p>` : ''}</div></div></section>${receipt()}<section class="section both-padd" data-wr-material-region="about-detail"><div class="container mp-about-detail"><div>${flower}<h2 class="h2" ${mark('about-detail-headline')}>${multiline(text('about-detail-headline'))}</h2><p class="body-l" ${mark('about-detail-description')}>${esc(text('about-detail-description'))}</p>${button('catalog', 'primary-cta')}</div><figure>${photo('about-detail-image')}</figure></div></section>`;
  if (page === 'contact') body = `${pageHeading('contact')}<section class="section both-padd" data-wr-material-region="contact"><div class="container mello-contact-layout"><aside class="mp-contact-panel"><div class="photo-block">${photo('contact-scene')}</div>${contactDetails()}${ctx.socials ? `<div class="mp-socials">${ctx.socials}</div>` : ''}</aside><div class="mello-form-card"><h2 class="h3 h3-small" ${mark('contact-form-headline')}>${esc(text('contact-form-headline'))}</h2><p class="body-m" ${mark('contact-form-description')}>${esc(text('contact-form-description'))}</p>${ctx.inquiryFormHtml}</div></div></section>`;
  const logo = draft.company.logoAssetId ? ctx.brandLogo : `<span class="logo-font">${esc(draft.company.name)}</span>`;
  const nav = `${enhanced ? route('home', `<span class="emphasis-l">${esc(ui.home)}</span>`, 'menu-link') : ''}${route('catalog', `<span class="emphasis-l">${esc(ui.catalog)}</span>`, 'menu-link')}${route('about', `<span class="emphasis-l">${esc(lang === 'en' ? 'About us' : ui.about)}</span>`, 'menu-link')}`;
  const header = `<a class="mp-skip" href="#main">${esc(ui.skip)}</a><header class="header"${enhanced ? ' data-wr-nav-layout="stacked-editorial"' : ''}><div class="info-bar"><div class="mp-info-bar">${esc(draft.company.name)} ${flower} ${selected('scene').map(product => esc(translateProduct(product).name)).join(' · ')}</div></div><div class="menu"><div class="container"><div class="menu-content">${route('home', enhanced ? `${flower}${logo}${flower}` : logo, 'logo')}<nav class="menu-links" aria-label="${esc(ui.menu)}">${nav}</nav>${button()}${draft.languages.length > 1 ? `<div class="mp-languages">${ctx.languageLinks}</div>` : ''}</div></div></div></header>`;
  const closing = `<section class="section both-padd black mp-closing" data-wr-material-region="closing-enquiry"><div class="container">${heading('closing')}<div class="mp-closing-links">${button()}${draft.company.email ? `<a class="handwritten-l" href="mailto:${esc(draft.company.email)}">${esc(draft.company.email)}</a>` : ''}</div></div></section>`;
  const footer = `<footer class="footer"><div class="container"><div class="footer-content"><div class="footer-info">${route('home', logo, 'logo')}<div class="mp-footer-links">${nav}${route('contact', esc(ui.contact), 'menu-link')}${ctx.socials}</div><p class="body-m">© ${new Date().getUTCFullYear()} ${esc(draft.company.name)} · ${esc(ui.rights)}</p></div></div></div></footer>`;
  const palette = materials.visual.palette;
  const color = (value: string, fallback: string) => /^#[a-f\d]{6}$/i.test(value) ? value : fallback;
  const variables = `--accent:${color(palette.primary, '#78bf30')};--black:${color(palette.text, '#284010')};--white:${color(palette.background, '#e9ebdf')};--mp-surface:${color(palette.surface, '#f3f4eb')};--black-opacity--80:${color(palette.mutedText, '#56624c')};`;
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(text(`${page}-seo-title`) || draft.company.name)}</title><meta name="description" content="${esc(text(`${page}-seo-description`))}">${options.preview ? '<meta name="robots" content="noindex,nofollow">' : ''}<style>${melloStyles}\n${productStyles}${enhanced ? melloEnhancedNavigation : ''}</style></head><body class="mello-coffee wr-mello-products" data-template="mello-coffee" data-wr-materials-revision="${esc(materials.contractRevision)}" style="${variables}">${header}<main id="main">${body}</main>${closing}${footer}</body></html>`;
}

const melloEnhancedNavigation = `
.wr-mello-products .header[data-wr-nav-layout] .menu-content{gap:18px 35px;padding:12px 0 20px}.wr-mello-products .header[data-wr-nav-layout] .logo{gap:28px}.wr-mello-products .header[data-wr-nav-layout] .logo-font{font-size:clamp(35px,4vw,56px)}.wr-mello-products .header[data-wr-nav-layout] .logo>.mp-flower{font-size:25px}.wr-mello-products .header[data-wr-nav-layout] .logo>.mp-flower:first-child{transform:rotate(-15deg)}.wr-mello-products .header[data-wr-nav-layout] .menu-links{gap:28px}.wr-mello-products .header[data-wr-nav-layout] .menu-link[aria-current=page]{text-decoration:underline;text-decoration-thickness:2px;text-underline-offset:7px}.wr-mello-products .header[data-wr-nav-layout] .menu-content>.button{border:2px solid var(--black);border-radius:8px;background:transparent;box-shadow:3px 3px 0 var(--black);padding:10px 16px;transform:rotate(-2deg)}.wr-mello-products .header[data-wr-nav-layout] .menu-content>.button:hover{transform:rotate(0) translateY(-2px)}.wr-mello-products .mp-hero-image>img,.wr-mello-products .mp-hero-image>picture>img{aspect-ratio:16/9}
@media(max-width:640px){.wr-mello-products .header[data-wr-nav-layout] .menu-content{gap:16px 22px;padding:5px 0 15px}.wr-mello-products .header[data-wr-nav-layout] .logo{gap:15px}.wr-mello-products .header[data-wr-nav-layout] .logo-font{font-size:38px}.wr-mello-products .header[data-wr-nav-layout] .logo>.mp-flower{font-size:20px}.wr-mello-products .header[data-wr-nav-layout] .menu-links{gap:18px}.wr-mello-products .header[data-wr-nav-layout] .menu-link .emphasis-l{font-size:14px}.wr-mello-products .header[data-wr-nav-layout] .menu-content>.button{font-size:13px;padding:9px 13px}}
`;

const productStyles = `
.wr-mello-products :is(h1,h2,h3,p,a,span,dd,li){overflow-wrap:anywhere}.wr-mello-products figure{margin:0}.wr-mello-products :is(.menu-content,.mp-detail,.mp-about-story,.mp-about-detail,.mp-featured,.mello-contact-layout)>*{min-width:0}.wr-mello-products [hidden]{display:none!important}
.wr-mello-products .mp-skip{position:fixed;top:-100px;left:16px;padding:12px 18px;background:var(--white);z-index:100}.wr-mello-products .mp-skip:not(:focus){clip-path:inset(50%)}.wr-mello-products .mp-skip:focus{top:12px}.wr-mello-products .mp-flower{font-size:48px;line-height:1}.wr-mello-products .mp-info-bar{display:flex;align-items:center;justify-content:center;gap:18px;padding:10px 20px;max-width:1328px;margin:auto;text-align:center;font-size:12px}.wr-mello-products .mp-info-bar .mp-flower{font-size:22px;flex-shrink:0}.wr-mello-products .logo img{max-width:180px;max-height:60px;object-fit:contain}.wr-mello-products .header{position:relative;gap:24px}.wr-mello-products .menu-content{flex-direction:row;flex-wrap:wrap;justify-content:center;gap:14px 24px}.wr-mello-products .menu-content>.logo{display:flex;flex-basis:100%;justify-content:center}.wr-mello-products .menu-content>.button{padding:14px 20px}.wr-mello-products .hero{padding-top:64px}.wr-mello-products .menu-content>.button{flex-shrink:0}.wr-mello-products .logo-font{font-size:clamp(25px,3vw,42px)}
.wr-mello-products .mp-page-heading{text-align:center;padding-top:64px}.wr-mello-products .mp-page-heading .label{justify-content:center}.wr-mello-products .mp-page-heading h1{max-width:960px;margin:24px auto}.wr-mello-products .mp-page-heading p{max-width:720px;margin:0 auto}.wr-mello-products .mp-hero-image{display:block!important;width:100%}.wr-mello-products .mp-hero-caption{display:flex;justify-content:space-between;gap:32px;margin-bottom:24px}.wr-mello-products .mp-hero-caption .product{position:static;display:flex;flex-direction:column;align-items:flex-start;gap:8px;max-width:65%}.wr-mello-products .mp-hero-note{display:flex;align-items:center;gap:18px;max-width:260px}.wr-mello-products .mp-hero-image>picture{display:block}.wr-mello-products .mp-hero-image>img,.wr-mello-products .mp-hero-image>picture>img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;border:3px solid var(--black);border-radius:24px;box-shadow:7px 7px 0 var(--black)}
.wr-mello-products .mp-ticker{overflow:hidden;margin-top:60px}.wr-mello-products .mp-ticker .ticker-line{display:flex;width:max-content;gap:38px;padding:20px 0;animation:none;transform:rotate(-2deg)}.wr-mello-products .mp-ticker .display-s{font-size:32px;white-space:nowrap}.wr-mello-products .mp-ticker .mp-flower{font-size:30px}
.wr-mello-products .mp-featured{display:grid;grid-template-columns:minmax(0,1.12fr) minmax(0,1fr);gap:24px}.wr-mello-products .mp-featured article{min-width:0;width:100%;height:auto}.wr-mello-products .mp-featured article:first-child{grid-row:span 2}.wr-mello-products .mp-featured .image-featured-menu-block{position:relative;min-height:420px;height:100%;padding:32px;justify-content:flex-end}.wr-mello-products .mp-featured article:first-child .image-featured-menu-block{min-height:864px}.wr-mello-products .mp-featured .image-featured-menu-block>picture{position:absolute;inset:0;width:100%;height:100%}.wr-mello-products .mp-featured img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.wr-mello-products .mp-featured .linear{position:absolute;inset:0;background:linear-gradient(180deg,transparent 36%,#000b 100%)}.wr-mello-products .mp-featured .block-items-wrapper{position:relative;z-index:1;color:#fff;gap:12px}.wr-mello-products .mp-featured .block-items-wrapper a{color:inherit}.wr-mello-products .mp-featured h3{font-size:clamp(26px,3vw,40px);line-height:1.1}.wr-mello-products .mp-featured[data-product-count="1"]{grid-template-columns:1fr;max-width:850px;margin:auto}.wr-mello-products .mp-featured[data-product-count="2"] article:first-child{grid-row:auto}.wr-mello-products .mp-featured[data-product-count="2"] .image-featured-menu-block{min-height:580px}
.wr-mello-products .mp-spec-list{margin:42px 0}.wr-mello-products .mp-spec-list .menu-item{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr) minmax(0,1fr);gap:32px;padding:28px 0;border-top:2px solid var(--black);align-items:start}.wr-mello-products .mp-spec-list .menu-item:last-child{border-bottom:2px solid var(--black)}.wr-mello-products .mp-spec-list h3{margin:8px 0 12px}.wr-mello-products .mp-spec-list p{margin:10px 0 0}.wr-mello-products .receipt{width:420px;background:var(--white)}.wr-mello-products .receipt-info{gap:24px}.wr-mello-products .receipt-header{gap:18px}.wr-mello-products .receipt-item{align-items:start;padding:12px 0}.wr-mello-products .receipt-item .emphasis-m{font-size:12px}.wr-mello-products .mp-receipt-bars{height:44px;margin:0 40px 40px;background:repeating-linear-gradient(90deg,var(--black) 0 2px,transparent 2px 5px,var(--black) 5px 9px,transparent 9px 12px)}
.wr-mello-products .mp-product-tabs{display:flex;flex-direction:column;margin-top:48px}.wr-mello-products .mp-panels>section+section{border-top:3px solid var(--black)}.wr-mello-products .spot-image{position:relative;min-height:0}.wr-mello-products .spot-image :is(img,picture){display:block;position:static;width:100%;height:100%}.wr-mello-products .spot-image img{aspect-ratio:3/2;object-fit:cover}.wr-mello-products .spot-info{background:var(--accent)}.wr-mello-products .spot-details{padding:36px;min-height:0;justify-content:center;gap:24px}.wr-mello-products .spot-tabs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr))}.wr-mello-products .spot-tab[aria-selected="true"]{background:var(--black);color:var(--white)}.wr-mello-products .spot-tab{border:0;border-top:3px solid var(--black);font:inherit;text-align:left;cursor:pointer}.wr-mello-products .spot-tab:focus-visible{outline:3px solid var(--black);outline-offset:-6px}.wr-mello-products .mp-product-tabs:not([data-wr-tabs-ready]) .spot-tabs{display:none}.wr-mello-products .mp-editorial-note{text-align:center;padding:60px 0 120px}.wr-mello-products .mp-editorial-note .display-m{max-width:1000px;margin:28px auto 36px;line-height:1.1}
.wr-mello-products .mp-catalog{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px}.wr-mello-products .mp-catalog-section{padding:60px 0 0}.wr-mello-products .mello-card{border:3px solid var(--black);border-radius:24px;overflow:hidden;box-shadow:5px 5px 0 var(--black);display:flex;flex-direction:column}.wr-mello-products .mp-main-image{display:block;background:#fff}.wr-mello-products .mp-main-image :is(picture,img){display:block;width:100%}.wr-mello-products .mp-main-image img{height:auto;aspect-ratio:1;object-fit:contain}.wr-mello-products .mp-card-copy{padding:24px;background:var(--mp-surface);flex:1;display:flex;flex-direction:column;gap:16px}.wr-mello-products .mp-card-copy :is(h2,p){margin:0}.wr-mello-products .mp-card-copy>a{margin-top:auto;padding-top:10px}.wr-mello-products .mp-catalog[data-product-count="1"]{grid-template-columns:minmax(0,480px);justify-content:center}.wr-mello-products .mp-catalog[data-product-count="2"]{grid-template-columns:repeat(2,minmax(0,1fr));max-width:1000px;margin:auto}
.wr-mello-products .mp-detail{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:70px;align-items:start}.wr-mello-products .mp-detail h1{font-size:clamp(40px,5vw,70px);margin:28px 0}.wr-mello-products .mp-detail-image{border:3px solid var(--black);border-radius:24px;overflow:hidden;background:white;box-shadow:7px 7px 0 var(--black)}.wr-mello-products .mp-detail-image :is(img,picture){display:block;width:100%}.wr-mello-products .mp-detail-image img{aspect-ratio:1;object-fit:contain;height:auto}.wr-mello-products .mp-detail dl{margin:28px 0}.wr-mello-products .mp-detail dl>div{display:grid;grid-template-columns:110px minmax(0,1fr);gap:20px;border-top:2px solid var(--black);padding:16px 0;font-size:14px}.wr-mello-products .mp-detail dt{font-weight:700}.wr-mello-products .mp-detail dd{margin:0}.wr-mello-products .mp-product-points{padding-left:22px;font-size:15px}
.wr-mello-products .mp-about-story{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr);gap:60px;align-items:center}.wr-mello-products .mp-about-detail{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,.85fr);gap:90px;align-items:center}.wr-mello-products .mp-about-detail h2{margin:26px 0}.wr-mello-products :is(.mp-about-story,.mp-about-detail) figure{border:3px solid var(--black);border-radius:24px;overflow:hidden;box-shadow:7px 7px 0 var(--black)}.wr-mello-products :is(.mp-about-story,.mp-about-detail) :is(img,picture){display:block;width:100%}.wr-mello-products .mp-about-story img{aspect-ratio:3/2;object-fit:cover}.wr-mello-products .mp-about-detail img{aspect-ratio:4/5;object-fit:cover}
.wr-mello-products .mp-contact-panel{border:3px solid var(--black);border-radius:24px;overflow:hidden;box-shadow:5px 5px 0 var(--black);background:var(--accent)}.wr-mello-products .mp-contact-panel .photo-block{padding:0;border:0;border-radius:0}.wr-mello-products .mp-contact-panel :is(img,picture){display:block;width:100%}.wr-mello-products .mp-contact-panel img{height:auto;aspect-ratio:6/5;object-fit:cover}.wr-mello-products .mp-contact-details{padding:32px;display:flex;flex-direction:column;gap:14px}.wr-mello-products .mp-contact-details :is(h3,p){margin:0}.wr-mello-products .mp-socials{display:flex;gap:16px;padding:0 32px 32px}.wr-mello-products .mello-form-card>p{margin:20px 0 30px}.wr-mello-products .mp-closing-links{display:flex;align-items:center;gap:40px;margin-top:36px}.wr-mello-products .mp-footer-links{display:flex;flex-wrap:wrap;align-items:center;gap:16px}.wr-mello-products .footer{padding-top:70px}.wr-mello-products .footer-info{gap:28px}.wr-mello-products .mp-languages{display:flex;gap:8px;font-size:12px}
@media(max-width:991px){.wr-mello-products .menu-content{flex-wrap:wrap;gap:14px}.wr-mello-products .menu-content>.logo{margin-right:auto}.wr-mello-products .menu-links{display:flex;gap:10px}.wr-mello-products .mp-catalog{grid-template-columns:repeat(2,minmax(0,1fr))}.wr-mello-products .mp-about-story,.wr-mello-products .mp-about-detail{gap:32px}.wr-mello-products .mp-detail{gap:36px}}
@media(max-width:767px){.wr-mello-products .header{gap:20px}.wr-mello-products .hero,.wr-mello-products .mp-page-heading{padding-top:40px}.wr-mello-products .mp-info-bar{font-size:10px;gap:8px}.wr-mello-products .menu-content>.logo{width:100%;justify-content:center}.wr-mello-products .menu-content{justify-content:center}.wr-mello-products .menu-links{gap:4px}.wr-mello-products .menu-link{padding:10px}.wr-mello-products .menu-link .emphasis-l{font-size:14px}.wr-mello-products .menu-content>.button{padding:12px 14px}.wr-mello-products .menu-content>.button .emphasis-l{font-size:13px}.wr-mello-products .mp-hero-caption{gap:16px}.wr-mello-products .mp-hero-caption .product{max-width:58%}.wr-mello-products .mp-hero-caption .display-s{font-size:22px}.wr-mello-products .mp-hero-note{max-width:35%;flex-direction:column;align-items:flex-start;gap:8px}.wr-mello-products .mp-hero-note .handwritten-l{font-size:16px}.wr-mello-products .mp-hero-image>img,.wr-mello-products .mp-hero-image>picture>img{box-shadow:4px 4px 0 var(--black)}.wr-mello-products .mp-featured{grid-template-columns:1fr;gap:20px}.wr-mello-products .mp-featured article:first-child{grid-row:auto}.wr-mello-products .mp-featured .image-featured-menu-block,.wr-mello-products .mp-featured article:first-child .image-featured-menu-block,.wr-mello-products .mp-featured[data-product-count="2"] .image-featured-menu-block{min-height:480px;padding:24px}.wr-mello-products .mp-spec-list .menu-item{grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.wr-mello-products .mp-spec-list .menu-item>div:first-child{grid-column:1/-1}.wr-mello-products .receipt{width:100%}.wr-mello-products .receipt-info{padding:30px 24px}.wr-mello-products .receipt-header .logo-font{font-size:32px}.wr-mello-products .spot-tabs{grid-template-columns:1fr}.wr-mello-products .spot-tab{flex-direction:row;gap:15px}.wr-mello-products .spot-details{padding:26px}.wr-mello-products .mp-editorial-note{padding:40px 0 70px}.wr-mello-products .mp-editorial-note .display-m{font-size:38px}.wr-mello-products .mp-catalog,.wr-mello-products .mp-catalog[data-product-count="2"],.wr-mello-products .mp-detail,.wr-mello-products .mp-about-story,.wr-mello-products .mp-about-detail{grid-template-columns:1fr}.wr-mello-products .mp-about-detail figure{max-width:480px}.wr-mello-products .mp-closing-links{align-items:flex-start;flex-direction:column;gap:24px}.wr-mello-products .mp-detail dl>div{grid-template-columns:1fr;gap:8px}.wr-mello-products .mp-footer-links{gap:8px}}
`;
