/** Only template-owned selectors are changed; no shared grid/flex or text background overrides. */
export const careflowOverrides = `
.cf-picture{display:contents}.careflow-healthcare img[data-careflow-image]{object-position:var(--cf-desktop-position,50% 50%)}html{scroll-behavior:smooth}.cf-pages{position:relative}.cf-pages-toggle{border:0;background:none;padding:0;cursor:pointer;color:inherit;font:inherit}.cf-pages-panel{position:absolute;top:100%;right:0;min-width:220px;padding:20px;background:white;box-shadow:0 12px 36px #19213d22;border-radius:16px;z-index:100}.cf-pages-panel a{display:block;padding:12px;color:#19213d}.cf-video-dialog{border:0;padding:0;background:#0b1020;width:min(1000px,94vw);max-width:94vw;border-radius:16px;color:white}.cf-video-dialog::backdrop{background:#000b}.cf-video-dialog iframe{width:100%;aspect-ratio:16/9;display:block;border:0}.cf-video-dialog button{background:transparent;color:white;border:0;padding:14px 20px;float:right;cursor:pointer;font:inherit}body.careflow-healthcare{overflow-x:clip}.careflow-healthcare [hidden]{display:none!important}
.careflow-healthcare :is(h1,h2,h3,p,a,label){overflow-wrap:break-word;word-break:normal}.careflow-healthcare :is(.w-layout-grid,.grid-2-columns,.grid-3-columns)>*{min-width:0}
.careflow-healthcare :is(.primary-button,.secondary-button){white-space:normal;line-height:1.35;text-align:center}
.careflow-healthcare .header{display:block}.careflow-healthcare .header-container-grid{position:relative;grid-template-columns:.8fr 1fr 1fr}.careflow-healthcare .nav-menu-middle{justify-self:center}.careflow-healthcare .list-nav-menu{gap:24px}.careflow-healthcare .nav-menu-wrapper{display:block}
.careflow-healthcare .hamburger-menu{border:0;background:#19213d;color:#fff}.cf-menu-icon{display:block;width:20px;height:14px;border-top:2px solid currentColor;border-bottom:2px solid currentColor}.careflow-healthcare a:focus-visible,.careflow-healthcare button:focus-visible,.careflow-healthcare [tabindex]:focus-visible{outline:3px solid #1d36b6;outline-offset:5px}
.careflow-healthcare .accordion-heading{cursor:pointer}.careflow-healthcare .accordion-body{height:auto;opacity:1}.careflow-healthcare .accordion-heading[aria-expanded=true] .primary-button-line.vertical{transform:rotate(90deg)}
.careflow-healthcare .w-slider-mask{display:flex;width:100%;max-width:100%;overflow:auto;scroll-snap-type:x mandatory;scrollbar-width:none;white-space:normal}.careflow-healthcare .w-slide{width:calc(100% / 3);min-width:0;flex:0 0 calc(100% / 3);scroll-snap-align:start}.careflow-healthcare .w-slider-mask::-webkit-scrollbar{display:none}.careflow-healthcare .w-slider{height:auto}.careflow-healthcare .w-slider-nav{display:none}
.cf-brand{text-decoration:none;display:inline-flex;gap:10px;align-items:center;font-weight:600;font-size:28px;line-height:1.15;max-width:230px;color:#1d36b6}.cf-brand img{max-width:155px;max-height:44px;object-fit:contain}.cf-brand-cross{font-size:34px;color:#6197de}.cf-footer-links{display:grid;grid-template-columns:1fr 1fr 1.3fr;gap:60px;width:100%}.cf-footer-links a{display:block;margin:14px 0;color:inherit}.cf-footer-links p{max-width:380px}.careflow-healthcare .footer-middle-v1{grid-template-columns:1fr}.cf-languages{display:flex;gap:12px;flex-wrap:wrap}.cf-languages a{font-size:14px}.cf-copyright{margin:0;font-size:15px}
.cf-inquiry{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;width:100%}.cf-inquiry .field{display:block;min-width:0;margin:0;font-weight:400}.cf-inquiry :is(input,select,textarea){display:block;width:100%;max-width:100%;margin:10px 0 0;padding:15px 18px;border:1px solid #c3d8e7;border-radius:8px;background:#fff;color:#182632;min-height:54px;font:inherit;font-size:16px;box-sizing:border-box}.cf-inquiry .full,.cf-inquiry .form-status{grid-column:1/-1}.cf-inquiry textarea{resize:vertical}.cf-inquiry .honeypot{position:absolute;left:-10000px;opacity:0;pointer-events:none}.cf-inquiry .primary-button{width:fit-content;max-width:100%;border:0;cursor:pointer}.cf-inquiry .form-status{font-size:15px;line-height:1.5}.cf-inquiry button:disabled{opacity:.6;cursor:not-allowed}.cf-form-card{padding:32px;border-radius:20px;background:#ebf4ff}.cf-form-card .cf-inquiry{grid-template-columns:1fr}.cf-form-card .cf-inquiry .full{grid-column:auto}
.cf-services{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.cf-service{min-width:0;background:#ebf4ff;border-radius:22px;overflow:hidden;padding:28px}.cf-service img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:14px;background:#fff;margin-bottom:24px}.cf-service h3{font-size:26px;line-height:1.2}.cf-service p{margin:18px 0}.cf-service .secondary-button{margin-top:14px}.cf-catalog{margin-top:60px}.cf-detail-gallery img{width:100%;height:auto;aspect-ratio:1.664;object-fit:contain;background:#f7f7f8;border-radius:20px}.cf-thumbs{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-top:16px}.cf-thumbs button{padding:4px;border:2px solid transparent;border-radius:12px;background:#ebf4ff;cursor:pointer;min-width:0}.cf-thumbs button[aria-pressed=true]{border-color:#1d36b6}.cf-thumbs img{aspect-ratio:1;border-radius:8px;object-fit:contain}.cf-detail-description{white-space:pre-line}.cf-preview-bar{padding:10px;text-align:center;background:#ebf4ff;color:#1d36b6;font:14px/1.4 'Inter Tight',sans-serif}.cf-empty{padding:48px;text-align:center;background:#ebf4ff;border-radius:20px}
.careflow-healthcare .content-inside-image.hero-content{max-width:100%}.careflow-healthcare .hero-card-v1{height:auto;overflow:hidden}.careflow-healthcare .hero-card-v1 .blur-circle{pointer-events:none}
@media(min-width:992px){.careflow-healthcare .hamburger-menu{display:none}}
@media(max-width:991px){.careflow-healthcare .header-container-grid{position:relative;grid-template-columns:1fr auto}.careflow-healthcare .nav-menu-middle{position:absolute;left:0;right:0;top:100%;width:100%;height:0}.careflow-healthcare .nav-menu-wrapper{display:none}.careflow-healthcare .nav-menu-wrapper.cf-menu-open{display:block;position:absolute;top:12px;left:0;right:0;width:100%;max-height:calc(100svh - 180px);overflow:auto;background:#fff;border:1px solid #c3d8e7;border-radius:16px;box-shadow:0 12px 40px #1d36b615;padding:20px;z-index:1000}.careflow-healthcare .cf-menu-open .list-nav-menu{display:flex;flex-direction:column;align-items:stretch;gap:0}.careflow-healthcare .cf-menu-open .link-nav-item a{display:block;padding:14px}.careflow-healthcare .nav-menu-right-side{gap:12px}.careflow-healthcare .hamburger-menu{display:grid;place-items:center;padding:8px;width:40px;min-width:40px;height:40px;min-height:40px}.careflow-healthcare .nav-menu-right-side .primary-button{display:none}.careflow-healthcare .w-slide{flex-basis:50%;width:50%}.cf-services{grid-template-columns:repeat(2,minmax(0,1fr))}.cf-footer-links{gap:30px}.careflow-healthcare .sticky-grid-v3{grid-template-columns:minmax(0,1fr)}.cf-form-card .cf-inquiry{grid-template-columns:repeat(2,minmax(0,1fr))}.cf-form-card .cf-inquiry .full{grid-column:1/-1}}
@media(max-width:600px){.careflow-healthcare img[data-careflow-image]{object-position:var(--cf-mobile-position,var(--cf-desktop-position,50% 50%))}.cf-services{grid-template-columns:1fr}.cf-footer-links{grid-template-columns:1fr;gap:24px}.cf-inquiry,.cf-form-card .cf-inquiry{grid-template-columns:1fr}.cf-inquiry .full{grid-column:auto}.cf-form-card{padding:24px}.cf-brand{font-size:24px;max-width:240px}.careflow-healthcare .w-slide{flex-basis:100%;width:100%}.cf-thumbs{gap:8px;grid-template-columns:repeat(4,minmax(0,1fr))}.careflow-healthcare .hero-card-v1{padding:28px 22px}.careflow-healthcare .hero-content{margin-left:12px;margin-right:12px}.careflow-healthcare .buttons-row{gap:12px}.careflow-healthcare .buttons-row>a{max-width:100%}.careflow-healthcare .header .container-default{padding-left:20px;padding-right:20px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.careflow-healthcare *{animation:none!important;transition:none!important}}
`;
