import {build} from 'esbuild';import {chromium} from '@playwright/test';import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {resolve,extname,sep} from 'node:path';import assert from 'node:assert/strict';
const output=resolve('artifacts/lumi-qa');await mkdir(output,{recursive:true});
await build({stdin:{contents:"export {renderSite,renderSiteFiles} from './src/templates';export {defaultDraft} from './src/worker/domain';export {lumiPages} from './src/shared/lumi-pages';",resolveDir:process.cwd(),loader:'ts'},outfile:output+'/renderer.mjs',bundle:true,format:'esm',platform:'node',keepNames:true});
const {renderSite,renderSiteFiles,defaultDraft,lumiPages}=await import(output+'/renderer.mjs');
const customer={...defaultDraft(),template:'lumi-business',buildBranch:'template',company:{...defaultDraft().company,name:'Acme Studio',email:'team@example.test',description:'Approved company facts'},products:[{id:'consulting',name:'Strategy Consulting',description:'Approved consulting description',material:'',dimensions:'',imageAssetId:'/templates/lumi/2c8138c7558a87e4.jpg'}]};
customer.products[0].imageAssetId='/templates/lumi/'+JSON.parse(await readFile('public/templates/lumi/sources.json','utf8')).assets.find(s=>s.url.includes('WUjX8RBz')).file;
const customerBanner={...customer,banners:[{id:'home',targets:['home'],kind:'images',mode:'image',fit:'cover',position:'center',contrast:'none',height:'auto',autoplay:false,interval:5,slides:[{assetId:customer.products[0].imageAssetId,alt:'First QA hero'},{assetId:customer.products[0].imageAssetId,alt:'Second QA hero'}]}]};
const draft=defaultDraft();draft.template='lumi-business';draft.brandColor='#48a7ff';const results=[];let server,browser,files;
try{server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');const match=u.pathname.match(/^\/__page\/([\w-]+)$/);if(match){res.setHeader('Content-Type','text/html');return res.end(renderSite(draft,{projectId:'preview',page:match[1],lang:'en',assetUrl:id=>id,inquiryUrl:'/api/inquiry',preview:true}))}const customerRoute=u.pathname.match(/^\/__customer\/([\w-]+)$/);if(customerRoute){res.setHeader('Content-Type','text/html');return res.end(renderSite(customerRoute[1]==='banner'?customerBanner:customer,{projectId:'customer',page:customerRoute[1]==='banner'?'home':customerRoute[1],productId:'consulting',lang:'en',assetUrl:id=>id,inquiryUrl:'/api/inquiry',preview:false}))}if(files?.[u.pathname.slice(1)]){res.setHeader('Content-Type','text/html');return res.end(files[u.pathname.slice(1)])}const path=resolve('public','.'+u.pathname);if(!path.startsWith(resolve('public')+sep))throw Error();res.setHeader('Content-Type',{'.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2','.mp4':'video/mp4'}[extname(path)]||'application/octet-stream');res.end(await readFile(path))}catch{res.statusCode=404;res.end('Not found')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;files=renderSiteFiles(draft,{projectId:'preview',assetUrl:id=>id,inquiryUrl:origin+'/api/inquiry',publicBaseUrl:origin,preview:false});
 browser=await chromium.launch({channel:'chrome'});
 for(const width of [1440,900,390,320]){const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('data:'))external.push(r.url())});
  for(const route of lumiPages.filter(p=>p!=='detail')){
   await page.goto(origin+'/__page/'+route,{waitUntil:'load',timeout:30000});
   await page.evaluate(async()=>{document.querySelectorAll('img').forEach(i=>i.loading='eager');await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})))});
   const metrics=await page.evaluate(()=>({h1:document.querySelectorAll('h1').length,overflow:document.documentElement.scrollWidth>innerWidth+1,broken:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),fonts:document.fonts.check('500 20px "Satoshi Variable"'),text:document.querySelector('h1')?.textContent}));
   results.push({width,route,...metrics});
   if(route==='home'){await page.screenshot({path:output+'/home-'+width+'.png',fullPage:true});await page.screenshot({path:output+'/home-top-'+width+'.png'});}
   if(route==='catalog'||route==='contact')await page.screenshot({path:output+'/'+route+'-'+width+'.png',fullPage:true});
   if(metrics.broken.length||metrics.overflow||metrics.h1!==1)console.log('CHECK',width,route,JSON.stringify(metrics));
   if(route==='contact')assert.equal(await page.locator('#inquiry button[type=submit]').isDisabled(),true);
   if(width<810&&route==='home'){await page.goto(origin+'/en/index.html');await page.getByRole('button',{name:'Open navigation'}).click();assert.equal(await page.locator('[data-lumi-mobile-menu]').isVisible(),true);await page.locator('[data-lumi-mobile-menu] a[data-wr-page="catalog"]').click();assert.match(page.url(),/catalog\/index.html/);}
  }
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.close();
 }
 const interaction=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 await interaction.goto(origin+'/en/index.html');
 const tabs=interaction.locator('[data-lumi-tabs] [role=tab]');if(await tabs.count()){await tabs.nth(1).click();assert.equal(await tabs.nth(1).getAttribute('aria-selected'),'true');await tabs.nth(1).press('ArrowRight');assert.equal(await tabs.nth(2).getAttribute('aria-selected'),'true');}
 const slider=interaction.locator('.framer-slideshow').first();const track=slider.locator('ul').first();const before=await track.getAttribute('style');await slider.getByRole('button',{name:'Next',exact:true}).click({force:true});assert.notEqual(await track.getAttribute('style'),before);
 let attempts=[];await interaction.route('**/api/inquiry',async route=>{attempts.push(route.request().postDataJSON());await route.fulfill({status:attempts.length===1?503:200,contentType:'application/json',body:JSON.stringify(attempts.length===1?{message:'Temporary failure'}:{ok:true})})});
 await interaction.goto(origin+'/__customer/contact?productId=consulting');
 await interaction.locator('#inquiry [name=name]').fill('QA Person');await interaction.locator('#inquiry [name=email]').fill('qa@example.test');await interaction.locator('#inquiry [name=message]').fill('Test message stays local.');
 await interaction.locator('#inquiry button[type=submit]').click();await interaction.locator('#inquiry [role=status]').filter({hasText:'Temporary failure'}).waitFor();
 await interaction.setViewportSize({width:390,height:1000});assert.equal(await interaction.locator('#inquiry [name=name]').inputValue(),'QA Person');await interaction.locator('#inquiry button[type=submit]').click();await interaction.locator('#inquiry [role=status]').filter({hasText:'Thank you'}).waitFor();
 await interaction.goto(origin+'/__customer/banner');
 for(const width of [1440,390]){await interaction.setViewportSize({width,height:1000});const banner=interaction.locator('[data-wr-banner="custom"]');assert.equal(await banner.count(),1);await banner.getByRole('button',{name:'Next banner'}).click();assert.equal(await banner.locator('[data-wr-slide]').nth(1).getAttribute('aria-hidden'),'false');assert.equal(await interaction.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}
 assert.equal(attempts.length,2);assert.equal(attempts[0].requestId,attempts[1].requestId);assert.equal(attempts[1].productId,'consulting');assert.equal(attempts[1].name,'QA Person');await interaction.close();
 await writeFile(output+'/report.json',JSON.stringify(results,null,2));assert(results.every(m=>m.h1===1&&!m.overflow&&!m.broken.length));console.log('Verified',results.length,'reference template pages; fonts, media, mobile menu and disabled preview forms.');
}finally{await browser?.close();await new Promise(r=>server?.close(r))}
