import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { unstable_startWorker } from 'wrangler';
import { chromium } from '@playwright/test';
const artifacts='artifacts/build-mode-review', origin='http://127.0.0.1:8797';
await mkdir(artifacts,{recursive:true});
execFileSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','d1','migrations','apply','web-radar','--local','--env','test','--persist-to',artifacts+'/state'],{stdio:'pipe'});
await writeFile(artifacts+'/index.png',Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1e0AAAAASUVORK5CYII=','base64'));
let worker,browser;
try {
  worker=await unstable_startWorker({config:'wrangler.jsonc',env:'test',dev:{server:{hostname:'127.0.0.1',port:8797},persist:artifacts+'/state',inspector:false,watch:false,logLevel:'error'}});
  await worker.ready;
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});
  const context=await browser.newContext({viewport:{width:1440,height:1100}});
  assert.equal((await context.request.post(origin+'/api/auth/test-login',{data:{identity:'owner'}})).status(),200);
  const page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin);
  await page.getByRole('button',{name:'创建网站',exact:true}).click();
  const modal=page.getByRole('dialog');
  await modal.getByRole('radio',{name:/模板建站/}).check();
  await modal.getByRole('button',{name:'创建并开始',exact:true}).click();
  const steps=page.getByRole('navigation',{name:'网站编辑步骤'});
  await steps.getByRole('button',{name:/选择模版/}).waitFor();
  assert.equal(await steps.getByRole('button').count(),3);
  assert.ok(!(await steps.innerText()).includes('需求沟通'));
  const id=new URL(page.url()).searchParams.get('project'); assert.ok(id);
  const endpoint=origin+'/api/projects/'+id;
  assert.equal((await(await context.request.get(endpoint)).json()).project.draft.buildBranch,'template');
  await page.getByLabel('公司 / 品牌名称',{exact:true}).fill('Retained brand');
  const modes=page.getByRole('region',{name:'建站方式切换'});
  await modes.getByRole('button',{name:'网址 / 设计稿建站',exact:true}).click();
  await page.locator('.clone-editor').waitFor();
  await page.getByLabel('参考网址',{exact:true}).fill('https://example.com');
  await page.locator('.clone-editor textarea').last().fill('Keep uploaded materials when switching modes.');
  await page.locator('.clone-editor input[type=file]').setInputFiles(artifacts+'/index.png');
  await page.getByText('已上传 1 个页面/素材文件').waitFor();
  await modes.getByRole('button',{name:'模板建站',exact:true}).click();
  await page.locator('.template-selector-container').waitFor();
  assert.equal(await steps.getByRole('button').count(),3);
  let data=(await(await context.request.get(endpoint)).json()).project;
  const assetId=data.draft.cloneConfig.uiImages[0].assetId;
  assert.equal(data.draft.buildBranch,'template');
  assert.equal(data.draft.company.name,'Retained brand');
  assert.equal(data.draft.cloneConfig.instructions,'Keep uploaded materials when switching modes.');
  await page.reload();
  await page.locator('.template-selector-container').waitFor();
  assert.equal(await steps.getByRole('button').count(),3);
  await page.screenshot({path:artifacts+'/template-three-steps.png'});
  await modes.getByRole('button',{name:'网址 / 设计稿建站',exact:true}).click();
  await page.locator('.clone-editor').waitFor();
  assert.equal(await page.getByLabel('参考网址',{exact:true}).inputValue(),'https://example.com');
  assert.equal(await page.locator('.clone-editor textarea').last().inputValue(),'Keep uploaded materials when switching modes.');
  await page.getByText('已上传 1 个页面/素材文件').waitFor();
  await page.reload();
  await page.locator('.clone-editor').waitFor();
  data=(await(await context.request.get(endpoint)).json()).project;
  assert.equal(data.draft.buildBranch,'clone');
  assert.equal(data.draft.cloneConfig.uiImages[0].assetId,assetId);
  // A failed save cannot claim the mode has switched or discard the existing workflow.
  await page.route('**/api/projects/'+id,async route=>{
    if(route.request().method()==='PUT')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Mode save unavailable'})});else await route.continue();
  });
  await modes.getByRole('button',{name:'模板建站',exact:true}).click();
  await page.getByText('Mode save unavailable',{exact:true}).waitFor();
  assert.equal(await modes.getByRole('button',{name:'网址 / 设计稿建站',exact:true}).getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('.clone-editor').count(),1);
  await page.unroute('**/api/projects/'+id);
  await page.setViewportSize({width:390,height:1100});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await modes.screenshot({path:artifacts+'/mobile-switch.png'});
  await modes.getByRole('button',{name:'模板建站',exact:true}).click();
  await page.locator('.template-selector-container').waitFor();
  // Existing unmarked drafts must not resume the hidden five-step workflow from a stale URL.
  const legacy=(await(await context.request.post(origin+'/api/projects',{data:{name:'Legacy missing mode',requestId:crypto.randomUUID(),buildBranch:'template'}})).json()).project;
  delete legacy.draft.buildBranch;
  assert.equal((await context.request.put(origin+'/api/projects/'+legacy.id,{data:{expectedVersion:legacy.version,draft:legacy.draft}})).status(),200);
  await page.setViewportSize({width:1440,height:1100});
  await page.goto(origin+'/?project='+legacy.id+'&tab=brief');
  await page.getByLabel('公司 / 品牌名称',{exact:true}).waitFor();
  assert.equal(await steps.getByRole('button').count(),3);
  assert.equal(new URL(page.url()).searchParams.get('tab'),'basics');
  await modes.getByRole('button',{name:'模板建站',exact:true}).click();
  await page.locator('.template-selector-container').waitFor();
  assert.equal((await(await context.request.get(origin+'/api/projects/'+legacy.id)).json()).project.draft.buildBranch,'template');
  const custom=(await(await context.request.post(origin+'/api/projects',{data:{name:'Existing custom mode',requestId:crypto.randomUUID(),buildBranch:'custom'}})).json()).project;
  await page.goto(origin+'/?project='+custom.id+'&tab=basics');
  await steps.getByRole('button',{name:/需求沟通/}).waitFor();
  assert.equal(await steps.getByRole('button').count(),5);
  await modes.getByRole('button',{name:'模板建站',exact:true}).click();
  await page.locator('.template-selector-container').waitFor();
  assert.equal(await steps.getByRole('button').count(),3);
  assert.deepEqual(errors,[]);
  console.log('PASS: new template projects persist template mode and show three steps; bidirectional mode switching saves pending company/URL/instructions/uploads; reload retains mode and assets; failed switch keeps current mode; stale legacy tab is corrected; existing custom projects remain usable; mobile switch has no overflow.');
} catch(error) {
  const page=browser?.contexts()[0]?.pages()[0];
  if(page){await page.screenshot({path:artifacts+'/failure.png',fullPage:true}).catch(()=>{});await writeFile(artifacts+'/failure.txt',await page.locator('body').innerText()).catch(()=>{});}
  throw error;
} finally {await browser?.close();await worker?.dispose();}
